export const OPCOES_MARCA_ARMA_B602 = [
  { codigo: "214", label: "(Arma Artesanal)" },
  { codigo: "1376", label: "(Fabricante Desconhecido)" },
  { codigo: "105", label: "A A Arms Inc." },
  { codigo: "106", label: "A.H. Fox Gun Co.-Sterlingworth" },
  { codigo: "107", label: "A.r. sales co." },
  { codigo: "108", label: "Accu-Match International" },
  { codigo: "110", label: "Accuracy Intl. Ltd." },
  { codigo: "109", label: "Accu-tek" },
  { codigo: "111", label: "Acha/Acha Hermanos" },
  { codigo: "112", label: "Acier Comprime" },
  { codigo: "113", label: "Adams" },
  { codigo: "114", label: "Adams Arms, LLC" },
  { codigo: "115", label: "Adler Arms Corporation" },
  { codigo: "116", label: "Adler/adlerwaffenwerke" },
  { codigo: "117", label: "ADP" },
  { codigo: "118", label: "Advanced Armaments, Inc" },
  { codigo: "119", label: "Advanced Small Arms Industries" },
  { codigo: "120", label: "Advantage arms usa inc" },
  { codigo: "121", label: "AEP- Ancien Estab. Pieper" },
  { codigo: "122", label: "Aero Precision" },
  { codigo: "123", label: "Agaoglu Aviation & Defense Industry (AHSS)" },
  { codigo: "124", label: "Agawam" },
  { codigo: "125", label: "AGSN" },
  { codigo: "126", label: "Aguila" },
  { codigo: "127", label: "Aguirre y aranzabal" },
  { codigo: "128", label: "Aguirre Y Cia" },
  { codigo: "129", label: "Akai Custom Guns" },
  { codigo: "130", label: "Akdal (Ucyildiz Arms Ind.Co.Ltd.)" },
  { codigo: "131", label: "AKKAR" },
  { codigo: "132", label: "Akliengeselischaft" },
  { codigo: "133", label: "Albert Wilhelm Wolf" },
  { codigo: "134", label: "Albrecht" },
  { codigo: "135", label: "Alchemy Arms" },
  { codigo: "136", label: "Aldazabal (Aaa)" },
  { codigo: "137", label: "Alfa" },
  { codigo: "138", label: "ALFA - PROJ spol s.r.o" },
  { codigo: "139", label: "Alkartasuna Fabrica De Armas" },
  { codigo: "140", label: "Allen & wheelock" },
  { codigo: "141", label: "Allen, ethan & co." },
  { codigo: "142", label: "Allies" },
  { codigo: "143", label: "Alpharms" },
  { codigo: "144", label: "Alpina Sport" },
  { codigo: "145", label: "Alpine" },
  { codigo: "146", label: "Alpine Industries" },
  { codigo: "147", label: "AMA - Ammunitionsarsenalet" },
  { codigo: "148", label: "American arms" },
  { codigo: "149", label: "American arms & ammo" },
  { codigo: "150", label: "American arms co." },
  { codigo: "151", label: "American Arms Inc." },
  { codigo: "152", label: "American arms international" },
  { codigo: "153", label: "American Derringer Co." },
  { codigo: "154", label: "American firearms mfg. co." },
  { codigo: "155", label: "American Frontier Firearms" },
  { codigo: "156", label: "American Spirit Arms Corp" },
  { codigo: "157", label: "American standard tool co." },
  { codigo: "158", label: "American Tactical Imports (ATI)" },
  { codigo: "159", label: "Amtec 2000, Inc." },
  { codigo: "160", label: "Anciens establishments pieper" },
  { codigo: "161", label: "Anderson Manufacturing" },
  { codigo: "162", label: "Angelo Zoli" },
  { codigo: "163", label: "Anschutz" },
  { codigo: "164", label: "Ant Tactical Arms (AT Arms)" },
  { codigo: "165", label: "Antonio Azpiri" },
  { codigo: "166", label: "Apache arms co." },
  { codigo: "167", label: "Apaolozo/Apaolozo Hermanos" },
  { codigo: "168", label: "Ar-7 Industries Llc" },
  { codigo: "169", label: "Aramberri Hermanos" },
  { codigo: "170", label: "Arana Y Cia" },
  { codigo: "171", label: "ARAUCA- Venusuala" },
  { codigo: "172", label: "Arcadia Machine &Tool (Amt)" },
  { codigo: "173", label: "Arcus Co." },
  { codigo: "174", label: "Arex Defense" },
  { codigo: "175", label: "Argento Industry" },
  { codigo: "176", label: "Arisaka" },
  { codigo: "177", label: "Arizmendi, Francisco" },
  { codigo: "178", label: "Arizmendi, norberto" },
  { codigo: "179", label: "ARMA" },
  { codigo: "180", label: "Armalite" },
  { codigo: "181", label: "Armament Technology Corp" },
  { codigo: "182", label: "Armas Bost" },
  { codigo: "183", label: "Armas EGO" },
  { codigo: "184", label: "Armas Erbi S.C.I." },
  { codigo: "185", label: "Armas GIB" },
  { codigo: "186", label: "Armas Jabe" },
  { codigo: "187", label: "Armas Trejo S.A." },
  { codigo: "188", label: "Armed (Turkey)" },
  { codigo: "189", label: "Armelegant Firearms Industry" },
  { codigo: "190", label: "Armeria Tucci Mario" },
  { codigo: "191", label: "Armi atis" },
  { codigo: "192", label: "Armi Fabri" },
  { codigo: "193", label: "Armi G. Varini" },
  { codigo: "194", label: "Armi Jager" },
  { codigo: "195", label: "Armi san marco" },
  { codigo: "196", label: "Armi san paolo" },
  { codigo: "197", label: "Armi tecniche de emilio rizzini" },
  { codigo: "198", label: "Arminex" },
  { codigo: "199", label: "Arminius" },
  { codigo: "200", label: "Arminius" },
  { codigo: "201", label: "Armitage international" },
  { codigo: "202", label: "Armory Gun Co." },
  { codigo: "203", label: "ARMSAN (Turkey)" },
  { codigo: "204", label: "Armsco" },
  { codigo: "205", label: "Armscor" },
  { codigo: "206", label: "Armscorp of America" },
  { codigo: "207", label: "Armstrong and Co." },
  { codigo: "208", label: "ARMTAC (Turkey)" },
  { codigo: "209", label: "Army & Navy" },
  { codigo: "210", label: "Arrieta & Arrizabalaga" },
  { codigo: "211", label: "Arrizabalaga & azanza" },
  { codigo: "212", label: "Arsenal Co. Of Bulgaria" },
  { codigo: "213", label: "Arsenal Firearms (Russia)" },
  { codigo: "215", label: "Aserma" },
  { codigo: "216", label: "ASI (Turkey)" },
  { codigo: "217", label: "Asil (Turkey)" },
  { codigo: "218", label: "Astra, Espana" },
  { codigo: "219", label: "ATA Arms" },
  { codigo: "220", label: "ATIS" },
  { codigo: "221", label: "Australian automatic arms" },
  { codigo: "222", label: "Australian International Arms" },
  { codigo: "223", label: "Auto Ordnance" },
  { codigo: "224", label: "Avsan" },
  { codigo: "225", label: "Awc Systems Technology" },
  { codigo: "226", label: "Axor Arms" },
  { codigo: "227", label: "Azul" },
  { codigo: "229", label: "B. Castellani" },
  { codigo: "230", label: "B.F. Arms Manufacturer" },
  { codigo: "231", label: "Bacon" },
  { codigo: "232", label: "Baford Arms,Inc./(Rt&M)" },
  { codigo: "233", label: "Bagual (Argentina)" },
  { codigo: "234", label: "Baikal" },
  { codigo: "235", label: "Baker gun co." },
  { codigo: "236", label: "Baldwin Co." },
  { codigo: "237", label: "Ballistic Advantage" },
  { codigo: "238", label: "Baltimore Arms Co." },
  { codigo: "239", label: "Barrett Firearms Mfg Co." },
  { codigo: "240", label: "Barthelmes" },
  { codigo: "241", label: "Bascaran, Martin A." },
  { codigo: "242", label: "Basque" },
  { codigo: "243", label: "Bauer firearms corp." },
  { codigo: "244", label: "Bauska arms" },
  { codigo: "245", label: "Bay State" },
  { codigo: "246", label: "Bayard" },
  { codigo: "247", label: "Bear Arms" },
  { codigo: "248", label: "Bear Creek Arsenal" },
  { codigo: "249", label: "Becker & Hollander" },
  { codigo: "250", label: "Beeman" },
  { codigo: "251", label: "Beistegui Bros., Libia" },
  { codigo: "252", label: "Belknap Hardware" },
  { codigo: "253", label: "Bellmore-johnson tool" },
  { codigo: "254", label: "Belmont firearms" },
  { codigo: "255", label: "Ben Franklin, Benjamin Franklin" },
  { codigo: "256", label: "Benelli, s. pa." },
  { codigo: "257", label: "Benjamin" },
  { codigo: "258", label: "Bentley (Philippines)" },
  { codigo: "6", label: "Bereta" },
  { codigo: "259", label: "Beretta" },
  { codigo: "260", label: "Beretta (FI Industries)" },
  { codigo: "261", label: "Bergeron" },
  { codigo: "262", label: "Bergerra" },
  { codigo: "263", label: "Bergmann (theodor)" },
  { codigo: "264", label: "Bernardelli, vincenzo" },
  { codigo: "265", label: "Bernedo" },
  { codigo: "266", label: "Bersa/bersa piccola" },
  { codigo: "267", label: "Bettinsoli" },
  { codigo: "268", label: "Birmingham small arms" },
  { codigo: "269", label: "Bisley Small Arms" },
  { codigo: "270", label: "Black Aces Tactical" },
  { codigo: "271", label: "Black Creek Labs" },
  { codigo: "272", label: "Black Rain Ordnance" },
  { codigo: "273", label: "Blaser jagdwaffen gmbh" },
  { codigo: "274", label: "Bliss & Goodyear" },
  { codigo: "275", label: "Blow" },
  { codigo: "276", label: "Blue Line" },
  { codigo: "277", label: "Boberg Arms" },
  { codigo: "278", label: "Boddecker" },
  { codigo: "279", label: "Bohica" },
  { codigo: "280", label: "Bohmesche waffenfabrik" },
  { codigo: "281", label: "Boito" },
  { codigo: "9", label: "Boito" },
  { codigo: "282", label: "Bolumburu, Gregorio" },
  { codigo: "283", label: "Bond Arms" },
  { codigo: "284", label: "Borchers" },
  { codigo: "285", label: "Bravo Company Manufacturing" },
  { codigo: "286", label: "Breda" },
  { codigo: "287", label: "Brescia Armas" },
  { codigo: "288", label: "Brevettate industria armi" },
  { codigo: "289", label: "BRG (Burgu Metal)" },
  { codigo: "290", label: "Bridge gun co." },
  { codigo: "291", label: "Bridgewater" },
  { codigo: "292", label: "Briley Manufacturing, Inc." },
  { codigo: "293", label: "British Sporting Arms" },
  { codigo: "294", label: "Brno zbrojovka" },
  { codigo: "295", label: "Broadhead Armory" },
  { codigo: "296", label: "Browning" },
  { codigo: "297", label: "Brugger & Thomet" },
  { codigo: "298", label: "Bruni (Replica Firearms)" },
  { codigo: "299", label: "Bryco Arms (Jennings)" },
  { codigo: "300", label: "Buddie arms co." },
  { codigo: "301", label: "Buffalo arms" },
  { codigo: "302", label: "Bul Transmark Ltd" },
  { codigo: "303", label: "Bulgarian State Factories" },
  { codigo: "304", label: "Bullseye Gun Works" },
  { codigo: "305", label: "Burgo" },
  { codigo: "306", label: "Busch" },
  { codigo: "307", label: "Bushmaster Firearms" },
  { codigo: "308", label: "Butler associates" },
  { codigo: "228", label: "B-West" },
  { codigo: "309", label: "Calico" },
  { codigo: "310", label: "Calwestco inc." },
  { codigo: "311", label: "Canadian Industries Ltd. (CIL)" },
  { codigo: "312", label: "Canik (Turkey)" },
  { codigo: "313", label: "Canuck" },
  { codigo: "314", label: "Caracal" },
  { codigo: "315", label: "Carcano" },
  { codigo: "316", label: "Carpati" },
  { codigo: "317", label: "Caspian arms ltd" },
  { codigo: "7", label: "Castelo" },
  { codigo: "318", label: "Cat Co" },
  { codigo: "319", label: "Cavalry Arms" },
  { codigo: "320", label: "CAVIM" },
  { codigo: "1", label: "CBC" },
  { codigo: "321", label: "Cbc (cia brazileria de cartuchos)" },
  { codigo: "322", label: "CD Defense" },
  { codigo: "323", label: "CDS" },
  { codigo: "324", label: "Celta" },
  { codigo: "325", label: "Centaure" },
  { codigo: "326", label: "Century Arms" },
  { codigo: "327", label: "Century International Arms" },
  { codigo: "328", label: "Century Mfg., Inc." },
  { codigo: "329", label: "Ceska Zbrojovka" },
  { codigo: "330", label: "Ceska zbrojovka" },
  { codigo: "331", label: "Cetme" },
  { codigo: "332", label: "Challenger mfg. corp." },
  { codigo: "333", label: "Champion" },
  { codigo: "334", label: "Chapuis Armes" },
  { codigo: "335", label: "Charles Daly" },
  { codigo: "336", label: "Charter arms" },
  { codigo: "337", label: "Chiappa Firearms" },
  { codigo: "338", label: "Chicago arms co." },
  { codigo: "339", label: "Chicago derringer corp." },
  { codigo: "340", label: "Chinese" },
  { codigo: "341", label: "Chip Mccormick Corp." },
  { codigo: "342", label: "Chipmunk manufacturing co." },
  { codigo: "343", label: "Churchill" },
  { codigo: "344", label: "Churchill, e.j. ltd." },
  { codigo: "345", label: "Cimarron Arms" },
  { codigo: "346", label: "Citadel (Armscor)" },
  { codigo: "347", label: "CK Arms" },
  { codigo: "348", label: "Claridge hi-tec" },
  { codigo: "349", label: "Clauberg" },
  { codigo: "350", label: "Clement" },
  { codigo: "351", label: "Clerke technicorp." },
  { codigo: "352", label: "Cleveland arms co." },
  { codigo: "353", label: "CMMG Inc." },
  { codigo: "354", label: "Coast to Coast" },
  { codigo: "355", label: "Cobra Enterprises" },
  { codigo: "356", label: "Cobra Enterprises of Utah Inc." },
  { codigo: "357", label: "Cobray" },
  { codigo: "358", label: "Cody mfg. corp." },
  { codigo: "359", label: "Cogswell and Harrison" },
  { codigo: "360", label: "Colony" },
  { codigo: "361", label: "Colt" },
  { codigo: "362", label: "Colt Canada Corporation" },
  { codigo: "363", label: "Columbia" },
  { codigo: "364", label: "Cometa" },
  { codigo: "365", label: "Commercial Products" },
  { codigo: "366", label: "Companhia" },
  { codigo: "367", label: "Competitor Corp., Inc." },
  { codigo: "368", label: "Component Metal Products" },
  { codigo: "369", label: "Concorde" },
  { codigo: "370", label: "Concorde (Philippines)" },
  { codigo: "371", label: "Connecticut Arms & Mfg. Co." },
  { codigo: "372", label: "Connecticut valley arms" },
  { codigo: "373", label: "Continental arms co." },
  { codigo: "374", label: "Continental Weapons Ltd." },
  { codigo: "375", label: "Cooey" },
  { codigo: "376", label: "Coonan arms inc." },
  { codigo: "377", label: "Cooper Arms" },
  { codigo: "378", label: "Cooper firearms mfg. co." },
  { codigo: "379", label: "Cop, inc." },
  { codigo: "380", label: "Core Rifle Systems" },
  { codigo: "381", label: "Corzo" },
  { codigo: "382", label: "Cotter & Co." },
  { codigo: "383", label: "Craft products" },
  { codigo: "384", label: "Crescent arms co.(sullivan)" },
  { codigo: "385", label: "Crickett" },
  { codigo: "386", label: "Criterion die & metal inc." },
  { codigo: "387", label: "Crossfire" },
  { codigo: "388", label: "Crossfire Llc" },
  { codigo: "389", label: "Crossman arms co." },
  { codigo: "390", label: "Crown city" },
  { codigo: "391", label: "Crucelegui Hermanos" },
  { codigo: "392", label: "Crucero" },
  { codigo: "393", label: "Cuno melcher" },
  { codigo: "394", label: "Cuno Melcher ME" },
  { codigo: "396", label: "Czech Sporting Arms" },
  { codigo: "397", label: "Czechoslovakian" },
  { codigo: "395", label: "CZ-Guns Trade" },
  { codigo: "398", label: "D C Industries" },
  { codigo: "399", label: "D max industries" },
  { codigo: "400", label: "D.g.f.m." },
  { codigo: "402", label: "Daewoo" },
  { codigo: "104", label: "Daewoo" },
  { codigo: "403", label: "Dagger" },
  { codigo: "404", label: "Daisy air rifle co." },
  { codigo: "405", label: "Daiwa Corp." },
  { codigo: "406", label: "Dakota" },
  { codigo: "407", label: "Dakota arms inc." },
  { codigo: "408", label: "Dan Arms" },
  { codigo: "409", label: "Daniel Defense" },
  { codigo: "410", label: "Dardick Corp" },
  { codigo: "401", label: "D'armes de chatellerault" },
  { codigo: "103", label: "D'armes de chatellerault" },
  { codigo: "411", label: "Darne" },
  { codigo: "412", label: "Daudsons Armoury (DSA)" },
  { codigo: "413", label: "Davenport, W.H.,Firearms Co." },
  { codigo: "414", label: "Davis industries" },
  { codigo: "416", label: "Davis, n. r. & sons" },
  { codigo: "415", label: "Davis-warner arms corp." },
  { codigo: "418", label: "Delphian arms co." },
  { codigo: "417", label: "Del-Ton" },
  { codigo: "419", label: "Demro products" },
  { codigo: "420", label: "Derya" },
  { codigo: "421", label: "Deryn" },
  { codigo: "422", label: "Detonics" },
  { codigo: "423", label: "Deutsche Waffen & Munitions Fabrik" },
  { codigo: "424", label: "Deutsche Werke" },
  { codigo: "425", label: "DFA Defense" },
  { codigo: "426", label: "DGIM (Mexico)" },
  { codigo: "427", label: "Diamond arms co." },
  { codigo: "428", label: "Diamondback Firearms" },
  { codigo: "429", label: "Diarm s.a." },
  { codigo: "430", label: "Dickinson Arms" },
  { codigo: "431", label: "Dickson" },
  { codigo: "432", label: "Diefke Wadie" },
  { codigo: "433", label: "Diemaco" },
  { codigo: "434", label: "Dixie Gun Works" },
  { codigo: "435", label: "Djuro Djakovic" },
  { codigo: "436", label: "Dlask Arms Corp" },
  { codigo: "437", label: "Dlo mfg., douglas l. oefinger" },
  { codigo: "438", label: "Doberman" },
  { codigo: "439", label: "Doki" },
  { codigo: "440", label: "Dominion Arms" },
  { codigo: "441", label: "Domino" },
  { codigo: "442", label: "Dornaus-dixon enterprises" },
  { codigo: "443", label: "DoubleStar Corp." },
  { codigo: "444", label: "Downsizer Corp" },
  { codigo: "445", label: "DPMS Panther Arms" },
  { codigo: "446", label: "Dreyse" },
  { codigo: "447", label: "Drulov" },
  { codigo: "448", label: "Dsa Inc." },
  { codigo: "449", label: "Dumoulin Freres" },
  { codigo: "450", label: "Duo" },
  { codigo: "451", label: "E & r machine company" },
  { codigo: "452", label: "E. Arthur Brown Company" },
  { codigo: "453", label: "E. R. Amantino" },
  { codigo: "454", label: "E.A.A. Corp." },
  { codigo: "455", label: "Eagle arms" },
  { codigo: "456", label: "Eagle gun company" },
  { codigo: "457", label: "East German" },
  { codigo: "458", label: "Eastern arms co." },
  { codigo: "459", label: "Eastfield" },
  { codigo: "460", label: "Eatonia" },
  { codigo: "461", label: "Echasa-eibar" },
  { codigo: "462", label: "Echave y arizmendi" },
  { codigo: "463", label: "Ed Brown Products, Inc." },
  { codigo: "464", label: "Eddy mfg co." },
  { codigo: "465", label: "Egyptian" },
  { codigo: "466", label: "Eidgenossische Waffenfabrik Bern" },
  { codigo: "467", label: "Ekol/Voltran" },
  { codigo: "468", label: "El Faisan" },
  { codigo: "469", label: "Elgin Arms" },
  { codigo: "470", label: "Elisco Tool Co. (Philippines)" },
  { codigo: "472", label: "EMEI (China)" },
  { codigo: "473", label: "EMF (Early Modern Firearms)" },
  { codigo: "471", label: "EM-GE" },
  { codigo: "474", label: "Empire state arms co." },
  { codigo: "475", label: "Emtan" },
  { codigo: "476", label: "Encom armament" },
  { codigo: "477", label: "Enfield" },
  { codigo: "478", label: "Enfield, albion" },
  { codigo: "479", label: "Enos James & Co." },
  { codigo: "480", label: "Enser Sportwaffen" },
  { codigo: "481", label: "Entreprise Arms, Inc" },
  { codigo: "482", label: "Erfurt Arsenal" },
  { codigo: "483", label: "Erma" },
  { codigo: "484", label: "Ernest Kazik" },
  { codigo: "485", label: "Ernst Thalmann Werke" },
  { codigo: "486", label: "Erquiaga Arms Co." },
  { codigo: "487", label: "Errasti, Antonio" },
  { codigo: "488", label: "ESC GmbH" },
  { codigo: "489", label: "Escodin" },
  { codigo: "490", label: "Escort" },
  { codigo: "491", label: "Esfac Inc., Erl Svendsen" },
  { codigo: "492", label: "Esperanza y Unceta" },
  { codigo: "493", label: "Essential Agencies Ltd." },
  { codigo: "494", label: "Essential Arms Inc." },
  { codigo: "495", label: "Essex arms company" },
  { codigo: "496", label: "Estul inc" },
  { codigo: "497", label: "Euroarms" },
  { codigo: "498", label: "Eusebio Arizaga" },
  { codigo: "499", label: "Euskaro" },
  { codigo: "500", label: "Excam" },
  { codigo: "501", label: "Excel Shotgun" },
  { codigo: "502", label: "Excelsior" },
  { codigo: "503", label: "Exel Arms Of America" },
  { codigo: "508", label: "F&L, Srl" },
  { codigo: "504", label: "F. Delu" },
  { codigo: "505", label: "F. pedretti" },
  { codigo: "506", label: "F.B. (Fabryka Broni Lukznik)" },
  { codigo: "507", label: "F.N." },
  { codigo: "509", label: "Fabarm, S.P.A." },
  { codigo: "510", label: "Fabbri" },
  { codigo: "511", label: "Fabrica d'armi fratelli pietta" },
  { codigo: "512", label: "Fabrica De Armas S.E.A.M." },
  { codigo: "513", label: "Fabrica de armas-iwa" },
  { codigo: "514", label: "Fabrica de material de guerra" },
  { codigo: "515", label: "Fabrica militar de armas portatiles" },
  { codigo: "516", label: "Fabricas de Armas Modernas" },
  { codigo: "517", label: "Fabrique D'Armes De Guerre De Prec" },
  { codigo: "518", label: "Fair" },
  { codigo: "519", label: "Falke world arms(world arms corp.)" },
  { codigo: "520", label: "FAMAE (Chile)" },
  { codigo: "521", label: "Famars Di Abbiatico Salvinelli" },
  { codigo: "522", label: "FAS, Italy" },
  { codigo: "523", label: "Fausti" },
  { codigo: "524", label: "FCPQ - Pulvoras Quimicas, Port." },
  { codigo: "525", label: "Feather enterprise" },
  { codigo: "526", label: "Fedarm" },
  { codigo: "527", label: "Federal engineering corp." },
  { codigo: "528", label: "Federal ordnance" },
  { codigo: "529", label: "FEG/Ferunion/Hungarian Arms Works" },
  { codigo: "530", label: "Feinwerkbau" },
  { codigo: "531", label: "Felk Industries" },
  { codigo: "532", label: "FFV" },
  { codigo: "533", label: "FI Industries" },
  { codigo: "534", label: "Fiala arms & equip. co." },
  { codigo: "535", label: "Fiat" },
  { codigo: "536", label: "Fie" },
  { codigo: "537", label: "Field Eddystone" },
  { codigo: "538", label: "Final Defense" },
  { codigo: "539", label: "Finnish lion" },
  { codigo: "540", label: "Fiocchi Italy" },
  { codigo: "541", label: "Fiocchi-Pardini" },
  { codigo: "542", label: "Firearms international corp." },
  { codigo: "543", label: "Firearms International Inc." },
  { codigo: "544", label: "Firestorm" },
  { codigo: "545", label: "Fleming Firearms" },
  { codigo: "546", label: "Flobert" },
  { codigo: "547", label: "Florida firearms" },
  { codigo: "548", label: "FMK Firearms" },
  { codigo: "549", label: "FN FAL" },
  { codigo: "550", label: "FN Herstal" },
  { codigo: "551", label: "FNA-Fabrica Armas de Mexico" },
  { codigo: "552", label: "FNP- FN Espana" },
  { codigo: "553", label: "Forehand & wadsworth" },
  { codigo: "554", label: "Forehand arms co." },
  { codigo: "555", label: "Fort Worth Firearms" },
  { codigo: "556", label: "Fox" },
  { codigo: "557", label: "Fox Air Guns" },
  { codigo: "558", label: "Fox Sterlingworth" },
  { codigo: "559", label: "Franchi" },
  { codigo: "560", label: "Francois Dumoulin & Co." },
  { codigo: "561", label: "Francotte, august" },
  { codigo: "562", label: "Frankfort Arsenal Inc." },
  { codigo: "563", label: "Frankonia" },
  { codigo: "564", label: "Fraser firearms corp." },
  { codigo: "565", label: "Fred Williams of Birmingham" },
  { codigo: "566", label: "Freedom arms co." },
  { codigo: "567", label: "Freedom Ordnance" },
  { codigo: "568", label: "French" },
  { codigo: "569", label: "French Service" },
  { codigo: "570", label: "Ftl marketing" },
  { codigo: "571", label: "Full metal jacket" },
  { codigo: "572", label: "Fyrberg, andrew" },
  { codigo: "573", label: "G. Mcmillan & Co., Inc." },
  { codigo: "574", label: "G.A.C." },
  { codigo: "575", label: "G.E. Lewis & Sons" },
  { codigo: "576", label: "Galesi" },
  { codigo: "577", label: "Gamba" },
  { codigo: "578", label: "Gamo" },
  { codigo: "579", label: "Garate anitua" },
  { codigo: "580", label: "Garate y mendibe" },
  { codigo: "581", label: "Garcia" },
  { codigo: "582", label: "Gaspar Arizaga" },
  { codigo: "583", label: "Gaucha-IGA" },
  { codigo: "584", label: "Gazanaga, isidro" },
  { codigo: "585", label: "Gecado" },
  { codigo: "586", label: "Geco" },
  { codigo: "587", label: "GECO-Gustav Genschow" },
  { codigo: "588", label: "Geha" },
  { codigo: "589", label: "General precision corp., triumph" },
  { codigo: "590", label: "Gerhard Gobharter G.M.B.H." },
  { codigo: "591", label: "German" },
  { codigo: "592", label: "German Sport Guns" },
  { codigo: "593", label: "Gerstenberger & eberwein" },
  { codigo: "594", label: "Gevarm" },
  { codigo: "595", label: "Gevelot" },
  { codigo: "596", label: "GForce Arms" },
  { codigo: "597", label: "Ghost Gun" },
  { codigo: "598", label: "Giacosa" },
  { codigo: "599", label: "Gianni '&' Valerio" },
  { codigo: "600", label: "Gilbert equipment co." },
  { codigo: "601", label: "GIRSAN" },
  { codigo: "602", label: "Glenfield" },
  { codigo: "603", label: "Glisenti" },
  { codigo: "604", label: "Global Arms" },
  { codigo: "605", label: "Globe" },
  { codigo: "606", label: "Globe Firearms (Canada)" },
  { codigo: "8", label: "Glock" },
  { codigo: "607", label: "Glock Inc." },
  { codigo: "608", label: "Gorosabel, pedro" },
  { codigo: "609", label: "Gradoga, f.a." },
  { codigo: "610", label: "Grand Power" },
  { codigo: "611", label: "Grand Power (Slovakia)" },
  { codigo: "612", label: "Great american" },
  { codigo: "613", label: "Great Lakes Firearms and Ammunition, LLC (GLFA)" },
  { codigo: "614", label: "Great western arms corp." },
  { codigo: "615", label: "Gregorelli & Umberti" },
  { codigo: "616", label: "Greifelt & company" },
  { codigo: "617", label: "Grendel Inc." },
  { codigo: "618", label: "Grey Ghost Precision" },
  { codigo: "619", label: "Griffon" },
  { codigo: "620", label: "Group industries" },
  { codigo: "621", label: "Guardian Mfg. Co." },
  { codigo: "622", label: "Guisasola bros." },
  { codigo: "623", label: "Gun Toys" },
  { codigo: "624", label: "Guncrafter Industries" },
  { codigo: "625", label: "Gunsmoke Enterprises" },
  { codigo: "626", label: "Gunworks limited" },
  { codigo: "627", label: "Gustaf, carl" },
  { codigo: "628", label: "Gustloff" },
  { codigo: "629", label: "Gyrojet" },
  { codigo: "630", label: "Gyttorp" },
  { codigo: "631", label: "H & R 1871 Inc." },
  { codigo: "632", label: "H. Dowal" },
  { codigo: "633", label: "H.S. Waffentechnik" },
  { codigo: "634", label: "Habicht" },
  { codigo: "635", label: "Haenel WuF AG" },
  { codigo: "636", label: "Haenel-schmeisser" },
  { codigo: "637", label: "Hafdasa" },
  { codigo: "638", label: "Hamilton Rifle Co." },
  { codigo: "639", label: "Hammerli" },
  { codigo: "640", label: "Hammerli" },
  { codigo: "641", label: "Hanover arms" },
  { codigo: "642", label: "Harrington & Richardson" },
  { codigo: "643", label: "Hartford Arms" },
  { codigo: "644", label: "Haskell (mfgr)" },
  { codigo: "645", label: "Hatsan Arms Co. (Turkey)" },
  { codigo: "646", label: "Hatton Industries" },
  { codigo: "647", label: "Hawk Industries Inc." },
  { codigo: "648", label: "Hebsacker Heym" },
  { codigo: "649", label: "Heckler & Koch" },
  { codigo: "650", label: "Hege" },
  { codigo: "651", label: "Hege Uberti" },
  { codigo: "652", label: "Hellenic Arms Industry" },
  { codigo: "653", label: "Helwan" },
  { codigo: "654", label: "Henry Repeating Arms" },
  { codigo: "655", label: "Henry Repeating Rifle Company" },
  { codigo: "656", label: "Herbert schmidt" },
  { codigo: "657", label: "Heritage mfg. inc." },
  { codigo: "658", label: "Herman Weihrauch" },
  { codigo: "659", label: "Hermann Weihrauch" },
  { codigo: "660", label: "Hesse Ltd" },
  { codigo: "661", label: "Heym" },
  { codigo: "662", label: "Hiawatha" },
  { codigo: "663", label: "High standard" },
  { codigo: "664", label: "Hijos De A. Echeverria (Vesta)" },
  { codigo: "665", label: "Hijos de Calixto Arrizabalaga" },
  { codigo: "666", label: "Hijos de F. Arizaga" },
  { codigo: "667", label: "Hima Arms" },
  { codigo: "668", label: "Hipoint" },
  { codigo: "669", label: "Hjs industries inc." },
  { codigo: "670", label: "Holland & Holland Ltd." },
  { codigo: "671", label: "Hollenbeck Gun Co." },
  { codigo: "672", label: "Hollis and Sons" },
  { codigo: "673", label: "Holloway and Naughton" },
  { codigo: "674", label: "Holmes Firearms Co." },
  { codigo: "675", label: "Holston Enterprises Inc" },
  { codigo: "676", label: "Honor Defense" },
  { codigo: "677", label: "Hood Firearms Co." },
  { codigo: "678", label: "Hopkins & Allen" },
  { codigo: "679", label: "Hotchkiss" },
  { codigo: "680", label: "Hovea" },
  { codigo: "681", label: "Hovedarsenalet, Christinana" },
  { codigo: "682", label: "Howa" },
  { codigo: "683", label: "HS Produkt" },
  { codigo: "684", label: "Hubenbecker" },
  { codigo: "685", label: "Hudson Mfg." },
  { codigo: "686", label: "Huglu" },
  { codigo: "687", label: "Hull Cartridge Co." },
  { codigo: "688", label: "Hungarian" },
  { codigo: "689", label: "Hungarian Arms Works" },
  { codigo: "690", label: "Hungarian State Factories" },
  { codigo: "691", label: "Hunt Group" },
  { codigo: "692", label: "Hunter arms co." },
  { codigo: "693", label: "Husqvarna" },
  { codigo: "694", label: "Hva" },
  { codigo: "695", label: "HWM (Germany)" },
  { codigo: "696", label: "Hy-Hunter Inc." },
  { codigo: "697", label: "I.a.g. (industria armi galesi)" },
  { codigo: "698", label: "I.O. Inc. (Inter Ordnance)" },
  { codigo: "699", label: "Iberia firearms" },
  { codigo: "700", label: "IBM (International Business Machine)" },
  { codigo: "701", label: "Iga" },
  { codigo: "702", label: "IM - Industria Mil. Colombia" },
  { codigo: "703", label: "IM Metal" },
  { codigo: "704", label: "Imbel" },
  { codigo: "705", label: "Imez (izhevsky mechanical works)" },
  { codigo: "706", label: "Imperial Gun Co., Ltd" },
  { codigo: "707", label: "Imperial metal products" },
  { codigo: "708", label: "Impex Import & Export" },
  { codigo: "709", label: "In Guns We Trust LLC. (IGWT)" },
  { codigo: "5", label: "INA" },
  { codigo: "710", label: "Indep/Fmp" },
  { codigo: "711", label: "Indesal, Industria De La Escopeta" },
  { codigo: "712", label: "Indian arms corp" },
  { codigo: "713", label: "Indumil (Colombia)" },
  { codigo: "714", label: "Industria Argentina" },
  { codigo: "715", label: "Industria armi bresciane" },
  { codigo: "716", label: "Industria de Armes Castelo S.A." },
  { codigo: "717", label: "Industria national de armes" },
  { codigo: "718", label: "Infinity Firearms" },
  { codigo: "719", label: "Inglis (Browning) Canada" },
  { codigo: "720", label: "Ingram" },
  { codigo: "721", label: "Inland (General Motors)" },
  { codigo: "722", label: "Interarms (mfgr)" },
  { codigo: "723", label: "Intercontinental Arms Inc." },
  { codigo: "724", label: "Interdynamics" },
  { codigo: "725", label: "International Antique Reproductions" },
  { codigo: "726", label: "Internationale ordnance" },
  { codigo: "727", label: "Intratec" },
  { codigo: "728", label: "Investarms, fabrica d'armi" },
  { codigo: "729", label: "IOF (Indian Ordnance Factory)" },
  { codigo: "730", label: "Iranian" },
  { codigo: "731", label: "Iraola Salaverria" },
  { codigo: "732", label: "Iraqi" },
  { codigo: "734", label: "Irwindale Arms Inc." },
  { codigo: "733", label: "Irwin-Pedersen" },
  { codigo: "735", label: "Ishapore Small Arms Factory" },
  { codigo: "736", label: "Israel Arms International" },
  { codigo: "737", label: "Israel Arms Ltd." },
  { codigo: "738", label: "Israel milty. ind." },
  { codigo: "739", label: "Israel Weapon Industries (IWI)" },
  { codigo: "740", label: "ISSC, Austria" },
  { codigo: "741", label: "Italguns" },
  { codigo: "742", label: "Italo GRA (Argentina)" },
  { codigo: "743", label: "Italy" },
  { codigo: "744", label: "Ithaca gun co." },
  { codigo: "745", label: "ITM (OOW Ohio, USA)" },
  { codigo: "746", label: "ITM (Switzerland)" },
  { codigo: "747", label: "Iver johnson" },
  { codigo: "748", label: "IWC" },
  { codigo: "749", label: "IWG" },
  { codigo: "750", label: "Izhmash" },
  { codigo: "751", label: "Izmech" },
  { codigo: "752", label: "J. & r. engineering co." },
  { codigo: "753", label: "J. Gaucher" },
  { codigo: "754", label: "J. Lagoas" },
  { codigo: "755", label: "J. Luis Urbiola" },
  { codigo: "756", label: "J. Saive Armes" },
  { codigo: "757", label: "J. Uriguen" },
  { codigo: "758", label: "J.C. Higgins" },
  { codigo: "760", label: "Jacquemart, J." },
  { codigo: "761", label: "Jaeger, armi" },
  { codigo: "762", label: "Jager & Co." },
  { codigo: "763", label: "Jaguar" },
  { codigo: "764", label: "Janssen Sons & Co." },
  { codigo: "765", label: "Japan" },
  { codigo: "766", label: "Jefferson Arms Co.,North Haven,Ct." },
  { codigo: "767", label: "Jennings Fine Tuning, Inc." },
  { codigo: "768", label: "Jennings firearms" },
  { codigo: "769", label: "Jericho (IMI)" },
  { codigo: "770", label: "Jersey Arms" },
  { codigo: "771", label: "Jian-Wei (China)" },
  { codigo: "772", label: "Jimenez Arms" },
  { codigo: "773", label: "Johnn Kevin Vittie/Johnny'S Armory" },
  { codigo: "774", label: "Johnson arms" },
  { codigo: "775", label: "Joslyn Firearms" },
  { codigo: "759", label: "J'S Pacific Enterprise /Brolin Ar" },
  { codigo: "776", label: "Jukar" },
  { codigo: "777", label: "Just Right Carbines" },
  { codigo: "778", label: "K&G Services" },
  { codigo: "779", label: "Kahr Arms" },
  { codigo: "780", label: "Kalashnikov Concern JSC" },
  { codigo: "781", label: "Kalashnikov Type" },
  { codigo: "782", label: "Kaschie (Schieder, Karl)" },
  { codigo: "783", label: "Kassnar Imports" },
  { codigo: "784", label: "Keep Brothers" },
  { codigo: "785", label: "Keiferie" },
  { codigo: "786", label: "Keltec, Cnc Industries,Inc." },
  { codigo: "787", label: "Kemen (Armas Kemen)" },
  { codigo: "788", label: "Kemira" },
  { codigo: "789", label: "Keseru" },
  { codigo: "790", label: "Kessler arms corp." },
  { codigo: "791", label: "Kettner" },
  { codigo: "792", label: "Keystone Sporting Arms" },
  { codigo: "793", label: "KFC (Kawabuchiya Firearms Co.)" },
  { codigo: "794", label: "Khan Arms" },
  { codigo: "795", label: "Kimar" },
  { codigo: "796", label: "Kimber" },
  { codigo: "797", label: "Kimel Industries" },
  { codigo: "798", label: "Kind" },
  { codigo: "799", label: "Kintrek, Inc." },
  { codigo: "800", label: "Klein Guenther" },
  { codigo: "801", label: "Knight'S Manufacturing Co." },
  { codigo: "802", label: "Koch Brexia Arms" },
  { codigo: "803", label: "Kodiak Defence Inc." },
  { codigo: "804", label: "Kodiak Defense Inc." },
  { codigo: "805", label: "Kodiak mfg. co." },
  { codigo: "806", label: "Kodial Industries" },
  { codigo: "807", label: "Kolb, H.M." },
  { codigo: "808", label: "Kommer" },
  { codigo: "809", label: "Kongsberg" },
  { codigo: "810", label: "Kongsberg Vapenfabrikk" },
  { codigo: "811", label: "Koon, H. Inc." },
  { codigo: "812", label: "Korth W." },
  { codigo: "813", label: "Krag-Jorgensen" },
  { codigo: "814", label: "Kral Arms" },
  { codigo: "815", label: "KRC Av (Turkey)" },
  { codigo: "816", label: "Krico" },
  { codigo: "817", label: "Kriegeskorte" },
  { codigo: "818", label: "Krieghoff firearms co." },
  { codigo: "819", label: "Kriss USA Inc." },
  { codigo: "820", label: "Ksn Industries Ltd." },
  { codigo: "821", label: "Ktg firearms" },
  { codigo: "822", label: "Kynoch" },
  { codigo: "823", label: "L. Soleil et Fils" },
  { codigo: "824", label: "L. W. Seecamp" },
  { codigo: "825", label: "L.a.r. manufacturing" },
  { codigo: "826", label: "La Caruna(Spanish Militar Arsenal)" },
  { codigo: "827", label: "Lahti" },
  { codigo: "828", label: "Lakefield Arms Ltd." },
  { codigo: "829", label: "Lakefield-Mossberg" },
  { codigo: "830", label: "Lames S.P.A." },
  { codigo: "831", label: "Lanber armas" },
  { codigo: "832", label: "Lanchester" },
  { codigo: "833", label: "Langenhan selbstlader" },
  { codigo: "834", label: "Lasagabaster Hermanos" },
  { codigo: "835", label: "Laseraim arms inc." },
  { codigo: "836", label: "Laurona" },
  { codigo: "837", label: "Lawson, harry company" },
  { codigo: "838", label: "Lazer Arms" },
  { codigo: "839", label: "Lazer Arms Co." },
  { codigo: "840", label: "Lazzeroni Arms Inc." },
  { codigo: "841", label: "Le Basque" },
  { codigo: "842", label: "Leader" },
  { codigo: "843", label: "Leader dynamics" },
  { codigo: "844", label: "Leader Trading" },
  { codigo: "845", label: "Lee arms co." },
  { codigo: "846", label: "Lee-enfield" },
  { codigo: "847", label: "Lefever" },
  { codigo: "848", label: "Leinad" },
  { codigo: "849", label: "Leinad, Inc." },
  { codigo: "850", label: "Les Baer Custom, Inc." },
  { codigo: "851", label: "Lever Arms" },
  { codigo: "852", label: "Lewis Machine & Tool" },
  { codigo: "853", label: "Liberty Arms International" },
  { codigo: "854", label: "Liberty Arms Works" },
  { codigo: "855", label: "Liberty Arms, Squires Bingham" },
  { codigo: "856", label: "Liege United Arms" },
  { codigo: "857", label: "Lignose" },
  { codigo: "858", label: "Linebaugh Custom (John W.)" },
  { codigo: "859", label: "Lion Brand" },
  { codigo: "860", label: "Lithgow" },
  { codigo: "861", label: "Ljungman" },
  { codigo: "862", label: "Ljutic industries inc." },
  { codigo: "863", label: "Llama (Gabilondo & Cia)" },
  { codigo: "864", label: "Loewe" },
  { codigo: "865", label: "Lone Wolf R&D LLC" },
  { codigo: "866", label: "Longines" },
  { codigo: "867", label: "Lorcin engineering" },
  { codigo: "868", label: "Loyola" },
  { codigo: "869", label: "Lucchini" },
  { codigo: "870", label: "Lucznik - Radom Arms Factory LLC." },
  { codigo: "871", label: "Luger" },
  { codigo: "872", label: "Luis Arrizabalaga" },
  { codigo: "873", label: "LWRC International" },
  { codigo: "874", label: "Lyman Gun Co." },
  { codigo: "875", label: "M.a.b." },
  { codigo: "876", label: "M.a.c." },
  { codigo: "877", label: "M.a.s." },
  { codigo: "878", label: "M.A.T." },
  { codigo: "879", label: "M.s. safari arms" },
  { codigo: "880", label: "M+M Industries" },
  { codigo: "881", label: "Maadi Company (Helwan)" },
  { codigo: "882", label: "Maadi-griffin" },
  { codigo: "883", label: "MAC (Stephensville, TX)" },
  { codigo: "884", label: "Maccabee Defense" },
  { codigo: "885", label: "Machine crafters, inc." },
  { codigo: "886", label: "Madsen" },
  { codigo: "887", label: "Magnum Research, Inc." },
  { codigo: "888", label: "Magtech" },
  { codigo: "889", label: "Mahely" },
  { codigo: "890", label: "Makarov" },
  { codigo: "891", label: "Makine ve Kimya Endustrisi (MKE Turkey)" },
  { codigo: "892", label: "Maltby & Henley" },
  { codigo: "893", label: "Manchester arms" },
  { codigo: "894", label: "Manfred Alberts" },
  { codigo: "895", label: "Mann, Fritz" },
  { codigo: "896", label: "Mannlicher" },
  { codigo: "897", label: "Mannlicher-Carcano" },
  { codigo: "898", label: "Manu-Arm" },
  { codigo: "899", label: "Manufrance" },
  { codigo: "900", label: "Manurhin s.a." },
  { codigo: "901", label: "Maple Ridge Armoury" },
  { codigo: "902", label: "Marble arms corp." },
  { codigo: "903", label: "Mario Beschi" },
  { codigo: "904", label: "Marixa Armas" },
  { codigo: "905", label: "Mark Legend" },
  { codigo: "906", label: "Marksman products inc." },
  { codigo: "907", label: "Marlin" },
  { codigo: "908", label: "Maroccini" },
  { codigo: "909", label: "Marochi & Figle" },
  { codigo: "910", label: "Martian" },
  { codigo: "911", label: "Martini-Henry" },
  { codigo: "912", label: "Masieri" },
  { codigo: "913", label: "Massachusetts Arms" },
  { codigo: "914", label: "MasterPiece Arms" },
  { codigo: "915", label: "Mauregan Arms Co." },
  { codigo: "916", label: "Mauser" },
  { codigo: "917", label: "Maverick arms (eagle pass, tx)" },
  { codigo: "918", label: "Mavi (di salvinelli angelo)" },
  { codigo: "919", label: "Mayer" },
  { codigo: "920", label: "Mayer & Reim" },
  { codigo: "921", label: "Mayer & Sohne" },
  { codigo: "922", label: "Mayer & Sohne" },
  { codigo: "923", label: "Maynard" },
  { codigo: "924", label: "McMillan" },
  { codigo: "925", label: "ME" },
  { codigo: "927", label: "Mears Arms Co." },
  { codigo: "928", label: "MEB" },
  { codigo: "926", label: "ME-CA" },
  { codigo: "929", label: "Mechem" },
  { codigo: "930", label: "Mega Arms" },
  { codigo: "931", label: "Meister products co.(mp express)" },
  { codigo: "932", label: "Melcher" },
  { codigo: "933", label: "Melcher Bruni" },
  { codigo: "934", label: "Melcher ME" },
  { codigo: "935", label: "Melior" },
  { codigo: "936", label: "Mendoza" },
  { codigo: "937", label: "Mendoza" },
  { codigo: "938", label: "Menegon, Renato" },
  { codigo: "939", label: "Menz, august" },
  { codigo: "940", label: "Mercury" },
  { codigo: "941", label: "Meriden firearms co." },
  { codigo: "942", label: "Meridian firearms co." },
  { codigo: "943", label: "Merkel, Gebruder" },
  { codigo: "944", label: "Merrill co." },
  { codigo: "945", label: "Merwin & Hulbert" },
  { codigo: "946", label: "Metallverken- Svenska" },
  { codigo: "947", label: "Metrillo" },
  { codigo: "948", label: "Mexican" },
  { codigo: "949", label: "MFS -Military Factory Sundarial" },
  { codigo: "950", label: "Michigan armament" },
  { codigo: "951", label: "Microtech Small Arms" },
  { codigo: "952", label: "Midland gun company" },
  { codigo: "953", label: "Miguel larranage" },
  { codigo: "954", label: "Mikros (Armes Unique)" },
  { codigo: "955", label: "Mil Inc." },
  { codigo: "956", label: "Military Armament Corp." },
  { codigo: "957", label: "Miroku firearm co." },
  { codigo: "958", label: "Mitchell arms" },
  { codigo: "959", label: "MK Arms Inc." },
  { codigo: "960", label: "Mk Ballistic Systems" },
  { codigo: "961", label: "Moa corp" },
  { codigo: "962", label: "Modern Muzzleloading" },
  { codigo: "963", label: "Molgora" },
  { codigo: "964", label: "Mondial" },
  { codigo: "965", label: "Monotype Scheme-Daimler" },
  { codigo: "966", label: "Moore & Roberts" },
  { codigo: "967", label: "Mosin-Nagant" },
  { codigo: "968", label: "Mossberg" },
  { codigo: "969", label: "Mugica, J.C." },
  { codigo: "970", label: "Musgrave" },
  { codigo: "971", label: "MWM Gillmann" },
  { codigo: "972", label: "NAACO" },
  { codigo: "973", label: "Nagant" },
  { codigo: "974", label: "Nambu" },
  { codigo: "975", label: "Nanno Hubenbecker" },
  { codigo: "10", label: "Não Aparente" },
  { codigo: "976", label: "National ordnance" },
  { codigo: "977", label: "National Postal Meter" },
  { codigo: "978", label: "Naughton" },
  { codigo: "979", label: "Navy arms co." },
  { codigo: "980", label: "Neumann" },
  { codigo: "981", label: "Neumann & Cie" },
  { codigo: "982", label: "Neumann Freres, Liege" },
  { codigo: "983", label: "New england firearms" },
  { codigo: "984", label: "New Frontier Armory" },
  { codigo: "985", label: "New Haven (Mossberg)" },
  { codigo: "986", label: "Newport" },
  { codigo: "987", label: "Nighthawk" },
  { codigo: "988", label: "NIKE" },
  { codigo: "989", label: "Nikko" },
  { codigo: "990", label: "Nitro hunter" },
  { codigo: "991", label: "Noble mfg. co." },
  { codigo: "992", label: "Nomad Defense Company" },
  { codigo: "993", label: "Norica (Norberto Arizmendi Y Cia)" },
  { codigo: "994", label: "Norinco (China North Industries Corporation)" },
  { codigo: "995", label: "Noris" },
  { codigo: "996", label: "Norma" },
  { codigo: "997", label: "North american arms" },
  { codigo: "998", label: "North Eastern Arms" },
  { codigo: "999", label: "North Korean State Factories" },
  { codigo: "1000", label: "Norton armament co./noramco" },
  { codigo: "1001", label: "Norway" },
  { codigo: "1002", label: "Norwich Falls Pistol Company" },
  { codigo: "1003", label: "Nowlin Custom Mfg" },
  { codigo: "1004", label: "Numrmich Arms Corp." },
  { codigo: "1005", label: "O.D.I. (Omega Defensive Industries)" },
  { codigo: "1006", label: "O.W.A." },
  { codigo: "1007", label: "Oficina Nacional de Armeiro" },
  { codigo: "1008", label: "Ojanguren y vidosa" },
  { codigo: "1009", label: "Olympia Pistole" },
  { codigo: "1010", label: "Olympic" },
  { codigo: "1011", label: "Olympic Arms Inc. (Safari Arms, Schu" },
  { codigo: "1012", label: "Omega Arms USA LLC" },
  { codigo: "1013", label: "Omega defensive industries" },
  { codigo: "1014", label: "OOW (Ohio Ordnance Works)" },
  { codigo: "1015", label: "Optima" },
  { codigo: "1016", label: "Optima (Hatsan)" },
  { codigo: "1017", label: "Orbea" },
  { codigo: "1018", label: "Ordnance design co." },
  { codigo: "1019", label: "Ordnance mfg. corp." },
  { codigo: "1020", label: "Ordnance technology" },
  { codigo: "1021", label: "Oregon Arms Ltd." },
  { codigo: "1022", label: "Orion" },
  { codigo: "1023", label: "Ortgies (Deutsche Werke)" },
  { codigo: "1024", label: "Otterup" },
  { codigo: "11", label: "Outro" },
  { codigo: "1025", label: "Oviedo" },
  { codigo: "1026", label: "Pac west arms" },
  { codigo: "1027", label: "Pachmayr gun works" },
  { codigo: "1028", label: "Page-Lewis" },
  { codigo: "1029", label: "Pallas" },
  { codigo: "1030", label: "Palmetto State Armory" },
  { codigo: "1031", label: "Para USA, LLC" },
  { codigo: "1033", label: "Paragon" },
  { codigo: "1034", label: "Paramount" },
  { codigo: "1032", label: "Para-Ordnance Mfg. Inc." },
  { codigo: "1035", label: "Pardini Armi Commerciale" },
  { codigo: "1036", label: "Pardus" },
  { codigo: "1037", label: "Parker" },
  { codigo: "1038", label: "Parker-hale" },
  { codigo: "1039", label: "Patriot Ordnance Factory Inc." },
  { codigo: "1040", label: "Pedersoli, Davide" },
  { codigo: "1041", label: "Penn Arms" },
  { codigo: "1042", label: "Perazzi" },
  { codigo: "1043", label: "Perazzi" },
  { codigo: "1044", label: "Perfecta" },
  { codigo: "1045", label: "Petr Novohradsky" },
  { codigo: "1046", label: "Phillips & Rodgers" },
  { codigo: "1047", label: "Phoenix arms co." },
  { codigo: "1048", label: "Phoenix Trinity" },
  { codigo: "1049", label: "Pietro Zanoletti" },
  { codigo: "1050", label: "Pietta, F.Lli" },
  { codigo: "1051", label: "Pioneer Arms Corp. (Poland)" },
  { codigo: "1052", label: "Pistole M.37 Or M.29" },
  { codigo: "1053", label: "Plainfield machine co." },
  { codigo: "1054", label: "Pointer" },
  { codigo: "1055", label: "Poland" },
  { codigo: "1056", label: "Poli Nicoletta" },
  { codigo: "1057", label: "Police Automatic Weapons" },
  { codigo: "1058", label: "Polish State Factories" },
  { codigo: "1059", label: "Polymer80, Inc." },
  { codigo: "1060", label: "Polytechnologies" },
  { codigo: "1061", label: "Pond, Lw Co." },
  { codigo: "1062", label: "Powell Knife Pistol Inc" },
  { codigo: "1063", label: "Ppi" },
  { codigo: "1064", label: "Prairie King" },
  { codigo: "1065", label: "Precise import corporation" },
  { codigo: "1066", label: "Precision industries" },
  { codigo: "1067", label: "Precision small parts" },
  { codigo: "1068", label: "Pretoria Arms" },
  { codigo: "1069", label: "Pretoria Arms Factory" },
  { codigo: "1070", label: "Pride of spain" },
  { codigo: "1071", label: "Primary Weapon Systems" },
  { codigo: "1072", label: "Privately Made Firearm" },
  { codigo: "1073", label: "Professional Ordnance" },
  { codigo: "1074", label: "Protector arms co." },
  { codigo: "1075", label: "Prvi Partizan â€? 'nny'" },
  { codigo: "1076", label: "Pucara" },
  { codigo: "1077", label: "Puma" },
  { codigo: "1078", label: "Purdey (james & sons)" },
  { codigo: "1079", label: "Quality Firearms Inc." },
  { codigo: "1080", label: "Quality Hardware" },
  { codigo: "1081", label: "Radelli" },
  { codigo: "1082", label: "Radical Firearms LLC." },
  { codigo: "1083", label: "Radom" },
  { codigo: "1084", label: "Raick Freres" },
  { codigo: "1085", label: "Ram-Line Inc." },
  { codigo: "1086", label: "Ranch & Silva" },
  { codigo: "1087", label: "Randall firearms manufacturing" },
  { codigo: "1088", label: "Rangemaster Precision Arms Ltd." },
  { codigo: "1089", label: "Ranger" },
  { codigo: "1090", label: "Ranger machine tool" },
  { codigo: "1091", label: "Raptor Arms Co., Inc." },
  { codigo: "1092", label: "Rast & Gasser" },
  { codigo: "1093", label: "Ratmil" },
  { codigo: "1094", label: "Raufoss" },
  { codigo: "1095", label: "Raven arms" },
  { codigo: "1096", label: "Rb industries" },
  { codigo: "1097", label: "RC Eximport, Italy" },
  { codigo: "1098", label: "Reck" },
  { codigo: "1099", label: "Recky" },
  { codigo: "1100", label: "Record Firearms" },
  { codigo: "1101", label: "Regent Arms" },
  { codigo: "1102", label: "Regina Koch" },
  { codigo: "1103", label: "Remington arms co." },
  { codigo: "1104", label: "REMSPORT" },
  { codigo: "1105", label: "Replica arms co." },
  { codigo: "1106", label: "Replica Firearm" },
  { codigo: "1107", label: "Republic Arms Of South Africa" },
  { codigo: "1108", label: "Republic Arms, Inc." },
  { codigo: "1109", label: "Retay Arms" },
  { codigo: "1110", label: "Retolaza/Retolaza Bros." },
  { codigo: "1111", label: "Revelation" },
  { codigo: "1112", label: "Revelation (Western Auto)" },
  { codigo: "1113", label: "Revolutionary Armory" },
  { codigo: "1114", label: "Revolutionary Mauler" },
  { codigo: "1115", label: "Rexio, S.R.L." },
  { codigo: "1116", label: "Rg industries" },
  { codigo: "1117", label: "Rheinische Metallwaren Und Maschin" },
  { codigo: "1118", label: "Rhoner" },
  { codigo: "1119", label: "Richard Burton '&' Co., Liege" },
  { codigo: "1120", label: "Richards, W." },
  { codigo: "1121", label: "Rigarmi / Rigarms(Rino Galesi)" },
  { codigo: "1122", label: "Rigby, John, & Co." },
  { codigo: "1123", label: "Riverside Arms Co." },
  { codigo: "1124", label: "Rizzini" },
  { codigo: "1125", label: "Rj braverman" },
  { codigo: "1126", label: "Robar Companies Inc." },
  { codigo: "1127", label: "Robinson Armament Co." },
  { codigo: "1128", label: "Rock island armory" },
  { codigo: "1129", label: "Rock Pistol Mfg.(Rpm)" },
  { codigo: "1130", label: "Rock River Arms, Inc." },
  { codigo: "1131", label: "Rock-Ola" },
  { codigo: "1132", label: "Rocky mountian arms corp." },
  { codigo: "1133", label: "Rogak Inc./Les" },
  { codigo: "1134", label: "Rogue Rifle Company, Inc." },
  { codigo: "1135", label: "Rohm" },
  { codigo: "1136", label: "Romanian" },
  { codigo: "1137", label: "Romanian State Factories" },
  { codigo: "1138", label: "Romarm/Cugir" },
  { codigo: "1139", label: "Romtehnica" },
  { codigo: "1140", label: "Rosco Arms Co." },
  { codigo: "1141", label: "Ross rifle co." },
  { codigo: "1142", label: "Rossi" },
  { codigo: "3", label: "Rossi" },
  { codigo: "1143", label: "Rota Luciano" },
  { codigo: "1144", label: "Roth-gasser" },
  { codigo: "1145", label: "Rottweil" },
  { codigo: "1146", label: "Royal Grinding And Machining" },
  { codigo: "1147", label: "Royal Ordnance Factory, Fazakerley" },
  { codigo: "1148", label: "Rpb industries" },
  { codigo: "1149", label: "Ruby arms co." },
  { codigo: "1150", label: "Ruby Extra (Gabilondo Y Cia)" },
  { codigo: "1151", label: "Ruger" },
  { codigo: "1152", label: "Rural" },
  { codigo: "1153", label: "Russian" },
  { codigo: "1154", label: "S.A.B.(Societa Armi Bresciane)" },
  { codigo: "1155", label: "S.a.c.m." },
  { codigo: "1156", label: "S.a.g.e.m." },
  { codigo: "1157", label: "S.A.M. Inc." },
  { codigo: "1158", label: "S.I.A.C.E." },
  { codigo: "1159", label: "S.I.G. (Swiss Industriel Gesellshaft)" },
  { codigo: "1160", label: "S.P.S. Guns" },
  { codigo: "1161", label: "Sabatti & Tanfoglio" },
  { codigo: "1162", label: "Sabatti Armi Spa" },
  { codigo: "1163", label: "Sabatti, Fabrica Italiani Armi" },
  { codigo: "1164", label: "Sabre Defence Industries" },
  { codigo: "1165", label: "Saco Defense" },
  { codigo: "1166", label: "Safari Arms Inc." },
  { codigo: "1167", label: "Saginaw Gear (General Motors)" },
  { codigo: "1168", label: "Sako" },
  { codigo: "1169", label: "Santa barbara" },
  { codigo: "1170", label: "Santos Modesto" },
  { codigo: "1171", label: "SAPL" },
  { codigo: "1172", label: "SAR Arms (Sarsilmaz)" },
  { codigo: "1173", label: "Sarasqueta, felix" },
  { codigo: "1174", label: "Sarasqueta, J J" },
  { codigo: "1175", label: "Sarasqueta, victor" },
  { codigo: "1176", label: "Sarriugarte, Francisco" },
  { codigo: "1177", label: "Sarruigarte, francisco" },
  { codigo: "1178", label: "Sauer & Sohn (Sons)- Sig" },
  { codigo: "1179", label: "Savage" },
  { codigo: "1180", label: "Sccy Industries" },
  { codigo: "1181", label: "Schilling" },
  { codigo: "1182", label: "Schmeisser" },
  { codigo: "1183", label: "Schmidt" },
  { codigo: "1184", label: "Schmidt-Rubin" },
  { codigo: "1185", label: "Schultz & Larsen (Otterup, Denmark)" },
  { codigo: "1186", label: "Schwarzlose, A.W." },
  { codigo: "1187", label: "Scorpio" },
  { codigo: "1188", label: "Sears" },
  { codigo: "1189", label: "Section Five Ltd." },
  { codigo: "1190", label: "Security industries of america" },
  { codigo: "1191", label: "Sedco industries" },
  { codigo: "1192", label: "Sedgley, R.F., Inc." },
  { codigo: "1193", label: "Select Weapon Systems Inc." },
  { codigo: "1194", label: "Sellier and Bellot" },
  { codigo: "1195", label: "Semmerling Corp." },
  { codigo: "1196", label: "Sendra corp." },
  { codigo: "1197", label: "Sentinel arms (ridgeway, pa)" },
  { codigo: "1198", label: "Seraphim Armory" },
  { codigo: "1199", label: "Seraphim Armory" },
  { codigo: "1200", label: "Serrifile inc." },
  { codigo: "1201", label: "Sgw enterprises" },
  { codigo: "1202", label: "Shadow Systems LLC" },
  { codigo: "1203", label: "Shandong 1st Machine Works" },
  { codigo: "1204", label: "Shapleighs" },
  { codigo: "1205", label: "Sharps, c. co." },
  { codigo: "1206", label: "Shattuck, C.S., Arms Co." },
  { codigo: "1207", label: "Sheridan products, inc." },
  { codigo: "1208", label: "Shilen Rifles, Incorporated" },
  { codigo: "1209", label: "Shinbisha Air Rifles" },
  { codigo: "1210", label: "Shinkosha" },
  { codigo: "1211", label: "Shinn-a-sipja" },
  { codigo: "1212", label: "Shooters Arms" },
  { codigo: "1213", label: "Shooters Arms Manufacturing" },
  { codigo: "1214", label: "Sidna" },
  { codigo: "1215", label: "Sierra Arms Co." },
  { codigo: "1216", label: "Sig Sauer" },
  { codigo: "1217", label: "Silma sporting guns" },
  { codigo: "1218", label: "Silver Eagle Shotguns" },
  { codigo: "1219", label: "Simmons Hardware Company" },
  { codigo: "1220", label: "Simonov" },
  { codigo: "1221", label: "Simson" },
  { codigo: "1222", label: "Sirkis industries ltd." },
  { codigo: "1223", label: "Sites s.p.a." },
  { codigo: "1224", label: "Skb Arms" },
  { codigo: "1225", label: "Skyy Industries" },
  { codigo: "1226", label: "Slazengers" },
  { codigo: "1227", label: "Smith & wesson" },
  { codigo: "4", label: "Smith and Wesson" },
  { codigo: "1228", label: "Smith Enterprises" },
  { codigo: "1229", label: "Smith, l.c." },
  { codigo: "1230", label: "Smith, Otis A." },
  { codigo: "1231", label: "SMLE" },
  { codigo: "1232", label: "SNS Industries" },
  { codigo: "1233", label: "Societe Moderne de Fabrication Mechanique" },
  { codigo: "1234", label: "Society robar" },
  { codigo: "1235", label: "Sodia, Franz" },
  { codigo: "1236", label: "Solothurn" },
  { codigo: "1238", label: "Sons of Liberty Gun Works" },
  { codigo: "1237", label: "SON-TEK" },
  { codigo: "1239", label: "Southwest Manufacturing" },
  { codigo: "1240", label: "Spanish Military" },
  { codigo: "1241", label: "Spartan Gunworks" },
  { codigo: "1242", label: "Spectre Ltd. (Canada)" },
  { codigo: "1243", label: "Spencer gun co." },
  { codigo: "1244", label: "Spesco" },
  { codigo: "1245", label: "Sphinx engineering co." },
  { codigo: "1246", label: "Spikes Tactical" },
  { codigo: "1247", label: "Spiller & burr" },
  { codigo: "1248", label: "Spitfire mgf. co." },
  { codigo: "1249", label: "Sportarmi" },
  { codigo: "1250", label: "Sportarms of florida" },
  { codigo: "1251", label: "Sportartikel KÃ¶nig" },
  { codigo: "1252", label: "Sportco" },
  { codigo: "1253", label: "Sporting Arms Mfg." },
  { codigo: "1254", label: "Spreewerk" },
  { codigo: "1255", label: "Springfield (Savage/Stevens)" },
  { codigo: "1256", label: "Springfield Armory, Geneseo, IL" },
  { codigo: "1257", label: "Springfield arms co." },
  { codigo: "1258", label: "Squibman, squires bingham" },
  { codigo: "1259", label: "Squires Bingham International Inc." },
  { codigo: "1260", label: "Stag Arms" },
  { codigo: "1261", label: "Staggs-Bilt Products" },
  { codigo: "1262", label: "Stallard Arms" },
  { codigo: "1263", label: "Stallard/maverick" },
  { codigo: "1264", label: "Standard arms co." },
  { codigo: "1265", label: "Standard Manufacturing" },
  { codigo: "1266", label: "Standard Products" },
  { codigo: "1267", label: "Stanley Andrewski,Jr./Stan Gunsmit" },
  { codigo: "1268", label: "Stanley arms co." },
  { codigo: "1269", label: "Star, bonifacio echeverria" },
  { codigo: "1270", label: "State Arms Gun Co." },
  { codigo: "1271", label: "Stefano, fausti" },
  { codigo: "1272", label: "Sten" },
  { codigo: "1273", label: "Sterling" },
  { codigo: "1274", label: "Sterling arms" },
  { codigo: "1275", label: "Sterlingworth" },
  { codigo: "1276", label: "Stevens Arms Company" },
  { codigo: "1277", label: "Steyr" },
  { codigo: "1278", label: "STI International" },
  { codigo: "1279", label: "Stirling" },
  { codigo: "1280", label: "Stock, Franz" },
  { codigo: "1281", label: "Stoeger arms" },
  { codigo: "1282", label: "Storm Lake Machine Inc." },
  { codigo: "1283", label: "Strayer tripp international" },
  { codigo: "1284", label: "Strayer-Voight Inc." },
  { codigo: "1285", label: "Striborg" },
  { codigo: "1286", label: "Strike Industries" },
  { codigo: "1287", label: "Sucessor De E. Guisasola" },
  { codigo: "1288", label: "Suinaga Y Aramberri" },
  { codigo: "1289", label: "Sun Devil Manufacturing" },
  { codigo: "1290", label: "Sundance Ind. Inc. (N. Hollywood, CA)" },
  { codigo: "1291", label: "Super Star" },
  { codigo: "1292", label: "Superior Arms Inc." },
  { codigo: "1293", label: "Supreme Ibargun" },
  { codigo: "1294", label: "Sure Shot" },
  { codigo: "1295", label: "Surefire Institute" },
  { codigo: "1296", label: "Surplus Ammo & Arms LLC" },
  { codigo: "1297", label: "Survival Arms" },
  { codigo: "1298", label: "Sw. mil 9/39" },
  { codigo: "1299", label: "Sw. mil 9/39B" },
  { codigo: "1300", label: "Sw. mil m/07" },
  { codigo: "1301", label: "Sw. mil m/67" },
  { codigo: "1302", label: "Sw. mil m/68B" },
  { codigo: "1303", label: "Swd (Cobray)" },
  { codigo: "1304", label: "Swedish" },
  { codigo: "1305", label: "Swiss Arms" },
  { codigo: "1307", label: "T&M (Truelove & MacLean)" },
  { codigo: "1306", label: "T.a.c." },
  { codigo: "1308", label: "Tactical Weapons Solutions" },
  { codigo: "1309", label: "Taiyojuki" },
  { codigo: "1310", label: "Tala" },
  { codigo: "1311", label: "Talon" },
  { codigo: "1312", label: "Tanfoglio giuseppe" },
  { codigo: "1313", label: "Tanfoglio, Fratelli, S.r.l." },
  { codigo: "1314", label: "Tara Group" },
  { codigo: "1315", label: "Targa" },
  { codigo: "1316", label: "Taurus" },
  { codigo: "2", label: "Taurus" },
  { codigo: "1317", label: "Tde" },
  { codigo: "1318", label: "Techno Arms Limited" },
  { codigo: "1319", label: "Tecni-Mec" },
  { codigo: "1320", label: "Terni" },
  { codigo: "1321", label: "Texas Armory" },
  { codigo: "1322", label: "Texas longhorn arms" },
  { codigo: "1323", label: "Thai Arms" },
  { codigo: "1324", label: "Thayer, Robinson & Cary" },
  { codigo: "1325", label: "The American" },
  { codigo: "1326", label: "Theate Freres, Liege" },
  { codigo: "1327", label: "Thermo Dynamic Systems" },
  { codigo: "1328", label: "Thomas Bland & Sons" },
  { codigo: "1329", label: "Thompson/center arms co." },
  { codigo: "1330", label: "Thureon Defense" },
  { codigo: "1331", label: "Tikka" },
  { codigo: "1332", label: "Tikkakoski" },
  { codigo: "1333", label: "Tippman Arms Co." },
  { codigo: "1334", label: "TISAS (Trabzon Gun Industry Corp.)" },
  { codigo: "1335", label: "Titan mfg. corp." },
  { codigo: "1336", label: "TMW Engineering (Autauga Arms)" },
  { codigo: "1337", label: "TNW Inc. (Technetwork)" },
  { codigo: "1338", label: "Tobin Arms Mfg. Co." },
  { codigo: "1339", label: "Tokagypt" },
  { codigo: "1340", label: "Tokarev" },
  { codigo: "1341", label: "Tomahawk" },
  { codigo: "1342", label: "TOZ" },
  { codigo: "1343", label: "Traditions, Inc" },
  { codigo: "1344", label: "Trejo" },
  { codigo: "1345", label: "Tressitu" },
  { codigo: "1346", label: "Triple s. development co." },
  { codigo: "1347", label: "Tristar" },
  { codigo: "1348", label: "Trocola aranzabal" },
  { codigo: "1349", label: "Truline" },
  { codigo: "1350", label: "Trushot (Germany)" },
  { codigo: "1351", label: "Truvelo" },
  { codigo: "1352", label: "Tula arsenal" },
  { codigo: "1353", label: "Typhoon" },
  { codigo: "1354", label: "Tyrol" },
  { codigo: "1355", label: "U.S. Patent Firearms Manufacturer" },
  { codigo: "1356", label: "U.S. Revolver Co." },
  { codigo: "1357", label: "U.s.a. military surplus" },
  { codigo: "1358", label: "Uberti, aldo" },
  { codigo: "1359", label: "UEE" },
  { codigo: "1360", label: "Ugartechea, ignacio" },
  { codigo: "1361", label: "Ultra-hi" },
  { codigo: "1362", label: "Ultramatic Sportwaffen Gmbh & Co." },
  { codigo: "1363", label: "Umarex" },
  { codigo: "1364", label: "UMC - Union Metalic Co." },
  { codigo: "1365", label: "Underwood" },
  { codigo: "1366", label: "Underwood-Elliot-Fisher and Co" },
  { codigo: "1367", label: "UNION" },
  { codigo: "1368", label: "Union arms co." },
  { codigo: "1369", label: "Union Switch & Signal" },
  { codigo: "1370", label: "Unique" },
  { codigo: "1371", label: "Unis" },
  { codigo: "1372", label: "United sporting arms" },
  { codigo: "1373", label: "United states arms corporation" },
  { codigo: "1374", label: "Universal firearms corp." },
  { codigo: "1375", label: "Uniwerke" },
  { codigo: "1377", label: "Uramex" },
  { codigo: "1378", label: "Urizar Y Cia (Tomas De)" },
  { codigo: "1379", label: "Urko" },
  { codigo: "1380", label: "US Carbine" },
  { codigo: "1381", label: "US Pistol Co." },
  { codigo: "1382", label: "US Rifle" },
  { codigo: "1383", label: "USFA" },
  { codigo: "1384", label: "UTAS, Turkey" },
  { codigo: "1385", label: "UZI" },
  { codigo: "1386", label: "Uzkon" },
  { codigo: "1387", label: "Uzumlu Arms" },
  { codigo: "1388", label: "V. G. Bently" },
  { codigo: "1389", label: "Valmet" },
  { codigo: "1390", label: "Valor Corp." },
  { codigo: "1391", label: "Valtro Stocchetta S.R.L." },
  { codigo: "1392", label: "Vanguard" },
  { codigo: "1393", label: "Vector/LEW" },
  { codigo: "1394", label: "Vega" },
  { codigo: "1395", label: "Vektor" },
  { codigo: "1396", label: "Velocity Firearms" },
  { codigo: "1397", label: "Venecedor" },
  { codigo: "1398", label: "Verney-Carron" },
  { codigo: "1399", label: "Verona" },
  { codigo: "1400", label: "Vetterli" },
  { codigo: "1401", label: "Victor aramberri & brothers" },
  { codigo: "1402", label: "Victoria" },
  { codigo: "1403", label: "Vihtavuori" },
  { codigo: "1404", label: "Voere" },
  { codigo: "1405", label: "Volquartsen Custom Ltd." },
  { codigo: "1406", label: "Volunteer enterprises" },
  { codigo: "1407", label: "Vore" },
  { codigo: "1408", label: "Vorenbach" },
  { codigo: "1409", label: "Vostok (Russia)" },
  { codigo: "1410", label: "Vulcan" },
  { codigo: "1411", label: "Vyatskie Polyany Machine Build Plan" },
  { codigo: "1412", label: "W.W. Greener, Ltd." },
  { codigo: "1413", label: "Waffenbrik-stendawerka" },
  { codigo: "1414", label: "Wagner" },
  { codigo: "1415", label: "Walker '&' Co." },
  { codigo: "1416", label: "Walther" },
  { codigo: "1417", label: "Warner arms corp." },
  { codigo: "1418", label: "Warrior (Turkey)" },
  { codigo: "1419", label: "Weatherby" },
  { codigo: "1420", label: "Weaver arms" },
  { codigo: "1421", label: "Weber" },
  { codigo: "1422", label: "Webley" },
  { codigo: "1423", label: "Webley & scott" },
  { codigo: "1424", label: "Weihrauch Arminius" },
  { codigo: "1425", label: "Weihrauch Hermann" },
  { codigo: "1426", label: "Werder" },
  { codigo: "1427", label: "Wesco ordnance" },
  { codigo: "1428", label: "Wesson arms, dan" },
  { codigo: "1429", label: "Wesson, frank" },
  { codigo: "1430", label: "Western Field" },
  { codigo: "1431", label: "Westley, richard" },
  { codigo: "1432", label: "Weston, J.J." },
  { codigo: "1433", label: "Westpoint" },
  { codigo: "1434", label: "Whamo mfg. co." },
  { codigo: "1435", label: "Whitney Arms Company" },
  { codigo: "1436", label: "Whitney mfg. co." },
  { codigo: "1437", label: "Whitneyville Armory" },
  { codigo: "1438", label: "Whitworth" },
  { codigo: "1439", label: "Wichita Arms" },
  { codigo: "1440", label: "Wike" },
  { codigo: "1441", label: "Wildey firearms" },
  { codigo: "1442", label: "Wilkinson" },
  { codigo: "1443", label: "Wilson Combat" },
  { codigo: "1444", label: "Winchester" },
  { codigo: "1445", label: "Windham Weaponry" },
  { codigo: "1446", label: "Winslow rifle co." },
  { codigo: "1447", label: "WOLF - Tula cart. Works" },
  { codigo: "1448", label: "Woodward, James, & Sons" },
  { codigo: "1449", label: "Workshop Made" },
  { codigo: "1450", label: "Wyoming arms" },
  { codigo: "1451", label: "Xythos" },
  { codigo: "1452", label: "Yamamoto Fa Mfg. Co." },
  { codigo: "1453", label: "Ydeal" },
  { codigo: "1454", label: "Yildiz" },
  { codigo: "1455", label: "Yugoslavian" },
  { codigo: "1456", label: "Yugoslavian State Factories" },
  { codigo: "1457", label: "Zabala, hermanos" },
  { codigo: "1458", label: "Zaklady Metalowe LUCZNIK" },
  { codigo: "1459", label: "Zamacola Hermanos" },
  { codigo: "1460", label: "Zaragosa, Fabrica d'Armas" },
  { codigo: "1461", label: "Zastava" },
  { codigo: "1462", label: "Zehner" },
  { codigo: "1463", label: "Zephyr" },
  { codigo: "1464", label: "Zm Weapons" },
  { codigo: "1465", label: "Zolarmi" },
  { codigo: "1466", label: "Zoli (antonio)" },
  { codigo: "1467", label: "Zoraki" },
  { codigo: "1468", label: "ZQI - Zenith Firearms" },
  { codigo: "1469", label: "Zulaica y Cia" },
  { codigo: "1470", label: "ZVI (Zbrojovka VsetÏ?n - Indet)" },
] as const
