import type { ProjetilReferencia } from '../types/projetil.types.js';

export const catalogoProjeteis: ProjetilReferencia[] = [
  {
    "id": "cbc-003",
    "calibre": ".22 RFCR",
    "tipo": "Ogival Ponta Arredondada",
    "massaGramas": 1.88,
    "diametroMinMm": 5.58,
    "diametroMaxMm": 5.61,
    "comprimentoMinMm": null,
    "comprimentoMaxMm": null,
    "situacao": "estimada"
  },
  {
    "id": "cbc-004",
    "calibre": ".22 RFCR Silhueta",
    "tipo": "Ogival Ponta Arredondada",
    "massaGramas": 1.88,
    "diametroMinMm": 5.58,
    "diametroMaxMm": 5.61,
    "comprimentoMinMm": null,
    "comprimentoMaxMm": null,
    "situacao": "estimada"
  },
  {
    "id": "cbc-005",
    "calibre": ".22 RFLR HV",
    "tipo": "Ogival Ponta Arredondada Ogival Ponta Afilada",
    "massaGramas": 2.59,
    "diametroMinMm": 5.58,
    "diametroMaxMm": 5.61,
    "comprimentoMinMm": null,
    "comprimentoMaxMm": null,
    "situacao": "estimada"
  },
  {
    "id": "cbc-006",
    "calibre": ".22 RFLR HV",
    "tipo": "Ogival Ponta Oca acabamento Cobreado",
    "massaGramas": 2.33,
    "diametroMinMm": 5.58,
    "diametroMaxMm": 5.61,
    "comprimentoMinMm": null,
    "comprimentoMaxMm": null,
    "situacao": "estimada"
  },
  {
    "id": "cbc-007",
    "calibre": ".22 RFLR Hyper HV",
    "tipo": "Cone Truncado acabamento Latonado",
    "massaGramas": 2.14,
    "diametroMinMm": 5.58,
    "diametroMaxMm": 5.61,
    "comprimentoMinMm": null,
    "comprimentoMaxMm": null,
    "situacao": "estimada"
  },
  {
    "id": "cbc-008",
    "calibre": ".22 RFLR Practice",
    "tipo": "Ogival Ponta Arredondada acabamento Grafitado",
    "massaGramas": 2.59,
    "diametroMinMm": 5.58,
    "diametroMaxMm": 5.61,
    "comprimentoMinMm": null,
    "comprimentoMaxMm": null,
    "situacao": "estimada"
  },
  {
    "id": "cbc-009",
    "calibre": ".22 RFLR Subsônico",
    "tipo": "Ogival Ponta Oca",
    "massaGramas": 2.59,
    "diametroMinMm": 5.58,
    "diametroMaxMm": 5.61,
    "comprimentoMinMm": null,
    "comprimentoMaxMm": null,
    "situacao": "estimada"
  },
  {
    "id": "cbc-010",
    "calibre": ".22 RFLR SV",
    "tipo": "Ogival Ponta Arredondada Ogival Ponta Afilada",
    "massaGramas": 2.59,
    "diametroMinMm": 5.58,
    "diametroMaxMm": 5.61,
    "comprimentoMinMm": null,
    "comprimentoMaxMm": null,
    "situacao": "estimada"
  },
  {
    "id": "cbc-012",
    "calibre": ".223 Remington",
    "tipo": "Encamisado Total Ponta Aguda (ETPT)",
    "massaGramas": 3.56,
    "diametroMinMm": 5.68,
    "diametroMaxMm": 5.7,
    "comprimentoMinMm": 18.8,
    "comprimentoMaxMm": 18.8,
    "situacao": "estimada"
  },
  {
    "id": "cbc-013",
    "calibre": ".223 Remington - PSP",
    "tipo": "Encamisado Ponta de Chumbo (EXPT)",
    "massaGramas": 3.56,
    "diametroMinMm": 5.68,
    "diametroMaxMm": 5.7,
    "comprimentoMinMm": 17.8,
    "comprimentoMaxMm": 17.8,
    "situacao": "estimada"
  },
  {
    "id": "cbc-014",
    "calibre": ".243 Winchester PSP",
    "tipo": "Encamisado Ponta de Chumbo (EXPT)",
    "massaGramas": 6.48,
    "diametroMinMm": 6.15,
    "diametroMaxMm": 6.17,
    "comprimentoMinMm": 26.7,
    "comprimentoMaxMm": 26.7,
    "situacao": "estimada"
  },
  {
    "id": "cbc-015",
    "calibre": ".25 Auto (6,35 BROW)",
    "tipo": "Encamisado Total Ogival (ETOG)",
    "massaGramas": 3.24,
    "diametroMinMm": 6.36,
    "diametroMaxMm": 6.38,
    "comprimentoMinMm": 11.7,
    "comprimentoMaxMm": 11.7,
    "situacao": "estimada"
  },
  {
    "id": "cbc-016",
    "calibre": ".30 M1 (.30 Carabina)",
    "tipo": "Encamisado Total Ogival (ETOG)",
    "massaGramas": 7.13,
    "diametroMinMm": 7.8,
    "diametroMaxMm": 7.83,
    "comprimentoMinMm": 17.2,
    "comprimentoMaxMm": 17.2,
    "situacao": "estimada"
  },
  {
    "id": "cbc-018",
    "calibre": ".30 M1 Carabina I (PSP)",
    "tipo": "Encamisado Ponta de Chumbo (EXOG)",
    "massaGramas": 7.13,
    "diametroMinMm": 7.8,
    "diametroMaxMm": 7.83,
    "comprimentoMinMm": 17.25,
    "comprimentoMaxMm": 17.25,
    "situacao": "estimada"
  },
  {
    "id": "cbc-019",
    "calibre": ".308 Winchester",
    "tipo": "Encamisado Total (ETPT) Ponta Aguda",
    "massaGramas": 9.72,
    "diametroMinMm": 7.81,
    "diametroMaxMm": 7.83,
    "comprimentoMinMm": 28.7,
    "comprimentoMaxMm": 28.7,
    "situacao": "estimada"
  },
  {
    "id": "cbc-020",
    "calibre": ".32 Auto",
    "tipo": "Chumbo Ogival (CHPP)",
    "massaGramas": 4.6,
    "diametroMinMm": 7.91,
    "diametroMaxMm": 7.93,
    "comprimentoMinMm": 11.5,
    "comprimentoMaxMm": 11.5,
    "situacao": "estimada"
  },
  {
    "id": "cbc-021",
    "calibre": ".32 Auto (7,65 BROW)",
    "tipo": "Encamisado Total Ogival (ETOG)",
    "massaGramas": 4.6,
    "diametroMinMm": 7.9,
    "diametroMaxMm": 7.92,
    "comprimentoMinMm": 11.5,
    "comprimentoMaxMm": 11.5,
    "situacao": "estimada"
  },
  {
    "id": "cbc-022",
    "calibre": ".32 Auto (7,65 BROW)",
    "tipo": "Encamisado Total Ponta Oca (EXPO)",
    "massaGramas": 4.6,
    "diametroMinMm": 7.9,
    "diametroMaxMm": 7.92,
    "comprimentoMinMm": 11.5,
    "comprimentoMaxMm": 11.5,
    "situacao": "estimada"
  },
  {
    "id": "cbc-023",
    "calibre": ".32 S&W",
    "tipo": "Chumbo Ogival (CHOG)",
    "massaGramas": 5.5,
    "diametroMinMm": 7.98,
    "diametroMaxMm": 8.0,
    "comprimentoMinMm": 13.0,
    "comprimentoMaxMm": 13.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-024",
    "calibre": ".32 S&W Canto Vivo",
    "tipo": "Canto Vivo cavidade no culote (CHCV)",
    "massaGramas": 6.35,
    "diametroMinMm": 7.98,
    "diametroMaxMm": 8.0,
    "comprimentoMinMm": 14.3,
    "comprimentoMaxMm": 14.3,
    "situacao": "estimada"
  },
  {
    "id": "cbc-025",
    "calibre": ".32 S&W Longo",
    "tipo": "Chumbo Ogival (CHOG)",
    "massaGramas": 6.35,
    "diametroMinMm": 7.98,
    "diametroMaxMm": 8.0,
    "comprimentoMinMm": 14.4,
    "comprimentoMaxMm": 14.4,
    "situacao": "estimada"
  },
  {
    "id": "cbc-026",
    "calibre": ".32 S&WL Silver Point",
    "tipo": "Semiencamisado Ponta de Chumbo Oca (EXPO)",
    "massaGramas": 6.35,
    "diametroMinMm": 7.98,
    "diametroMaxMm": 8.0,
    "comprimentoMinMm": 14.3,
    "comprimentoMaxMm": 14.3,
    "situacao": "estimada"
  },
  {
    "id": "cbc-027",
    "calibre": ".32-20 Winchester",
    "tipo": "Chumbo Ponta Plana (CHPP)",
    "massaGramas": 6.48,
    "diametroMinMm": 7.87,
    "diametroMaxMm": 7.9,
    "comprimentoMinMm": 14.4,
    "comprimentoMaxMm": 14.4,
    "situacao": "estimada"
  },
  {
    "id": "cbc-028",
    "calibre": ".357 Magnum",
    "tipo": "Semiencamisado Ponta de Chumbo Oca (EXPO)",
    "massaGramas": 10.24,
    "diametroMinMm": 9.07,
    "diametroMaxMm": 9.1,
    "comprimentoMinMm": 17.0,
    "comprimentoMaxMm": 17.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-029",
    "calibre": ".357 Magnum",
    "tipo": "Semiencamisado Ponta de Chumbo Plana (EXPP)",
    "massaGramas": 10.24,
    "diametroMinMm": 9.07,
    "diametroMaxMm": 9.1,
    "comprimentoMinMm": 17.0,
    "comprimentoMaxMm": 17.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-030",
    "calibre": ".357 Magnum",
    "tipo": "Semiencamisado Ponta de Chumbo Oca (EXPO)",
    "massaGramas": 8.1,
    "diametroMinMm": 9.07,
    "diametroMaxMm": 9.1,
    "comprimentoMinMm": 13.7,
    "comprimentoMaxMm": 13.7,
    "situacao": "estimada"
  },
  {
    "id": "cbc-031",
    "calibre": ".357 Magnum",
    "tipo": "Chumbo Semicanto Vivo (CSCV)",
    "massaGramas": 10.24,
    "diametroMinMm": 9.07,
    "diametroMaxMm": 9.1,
    "comprimentoMinMm": 17.6,
    "comprimentoMaxMm": 17.6,
    "situacao": "estimada"
  },
  {
    "id": "cbc-032",
    "calibre": ".357 Magnum",
    "tipo": "Chumbo Ponta Plana (CHPP)",
    "massaGramas": 10.24,
    "diametroMinMm": 9.07,
    "diametroMaxMm": 9.1,
    "comprimentoMinMm": 15.6,
    "comprimentoMaxMm": 15.6,
    "situacao": "estimada"
  },
  {
    "id": "cbc-033",
    "calibre": ".357 Magnum",
    "tipo": "Encamisado Total Ponta Oca (EXPO)",
    "massaGramas": 8.1,
    "diametroMinMm": 9.06,
    "diametroMaxMm": 9.08,
    "comprimentoMinMm": 14.0,
    "comprimentoMaxMm": 14.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-034",
    "calibre": ".38 CBC SPL Curto",
    "tipo": "Chumbo Ogival (CHOG)",
    "massaGramas": 8.1,
    "diametroMinMm": 9.07,
    "diametroMaxMm": 9.1,
    "comprimentoMinMm": 14.3,
    "comprimentoMaxMm": 14.3,
    "situacao": "estimada"
  },
  {
    "id": "cbc-035",
    "calibre": ".38 Special",
    "tipo": "Chumbo Ponta Plana (CHPP)",
    "massaGramas": 10.24,
    "diametroMinMm": 9.07,
    "diametroMaxMm": 9.1,
    "comprimentoMinMm": 15.6,
    "comprimentoMaxMm": 15.6,
    "situacao": "estimada"
  },
  {
    "id": "cbc-036",
    "calibre": ".38 Special com todas as versões de projétil",
    "tipo": "Chumbo Ogival (CHOG)",
    "massaGramas": 10.24,
    "diametroMinMm": 9.07,
    "diametroMaxMm": 9.1,
    "comprimentoMinMm": 18.8,
    "comprimentoMaxMm": 18.8,
    "situacao": "estimada"
  },
  {
    "id": "cbc-037",
    "calibre": ".38 Special com todas as versões de projétil",
    "tipo": "Chumbo Semicanto Vivo (CSCV)",
    "massaGramas": 10.24,
    "diametroMinMm": 9.07,
    "diametroMaxMm": 9.1,
    "comprimentoMinMm": 17.6,
    "comprimentoMaxMm": 17.6,
    "situacao": "estimada"
  },
  {
    "id": "cbc-038",
    "calibre": ".38 Special com todas as versões de projétil",
    "tipo": "Semiencamisado Ponta de Chumbo Oca (EXPO)",
    "massaGramas": 10.24,
    "diametroMinMm": 9.07,
    "diametroMaxMm": 9.1,
    "comprimentoMinMm": 17.0,
    "comprimentoMaxMm": 17.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-039",
    "calibre": ".38 SPL",
    "tipo": "Totalmente Encamisado Encamisado Obturado (EOOG)",
    "massaGramas": 10.24,
    "diametroMinMm": 9.06,
    "diametroMaxMm": 9.08,
    "comprimentoMinMm": 16.45,
    "comprimentoMaxMm": 16.45,
    "situacao": "estimada"
  },
  {
    "id": "cbc-040",
    "calibre": ".38 SPL + P",
    "tipo": "Encamisado Total Ponta Oca (EXPO)",
    "massaGramas": 8.1,
    "diametroMinMm": 9.06,
    "diametroMaxMm": 9.08,
    "comprimentoMinMm": 14.0,
    "comprimentoMaxMm": 14.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-041",
    "calibre": ".38 SPL + P Siiver Point",
    "tipo": "Encamisado Ponta Plana (ETPP) Niquelado",
    "massaGramas": 8.1,
    "diametroMinMm": 9.07,
    "diametroMaxMm": 9.1,
    "comprimentoMinMm": 13.2,
    "comprimentoMaxMm": 13.2,
    "situacao": "estimada"
  },
  {
    "id": "cbc-042",
    "calibre": ".38 SPL + P Siiver Point",
    "tipo": "Semiencamisado Ponta de Chumbo Oca (EXPO) Niquelado",
    "massaGramas": 8.1,
    "diametroMinMm": 9.07,
    "diametroMaxMm": 9.1,
    "comprimentoMinMm": 13.7,
    "comprimentoMaxMm": 13.7,
    "situacao": "estimada"
  },
  {
    "id": "cbc-043",
    "calibre": ".38 SPL +P",
    "tipo": "Semiencamisado Ponta de Chumbo Oca (EXPO)",
    "massaGramas": 10.24,
    "diametroMinMm": 9.07,
    "diametroMaxMm": 9.1,
    "comprimentoMinMm": 17.0,
    "comprimentoMaxMm": 17.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-044",
    "calibre": ".38 SPL +P",
    "tipo": "Semiencamisado Ponta de Chumbo Oca (EXPO)",
    "massaGramas": 8.1,
    "diametroMinMm": 9.07,
    "diametroMaxMm": 9.1,
    "comprimentoMinMm": 13.7,
    "comprimentoMaxMm": 13.7,
    "situacao": "estimada"
  },
  {
    "id": "cbc-045",
    "calibre": ".38 SPL Canto Vivo",
    "tipo": "Canto Vivo cavidade no culote (CHCV)",
    "massaGramas": 9.59,
    "diametroMinMm": 9.07,
    "diametroMaxMm": 9.1,
    "comprimentoMinMm": 16.0,
    "comprimentoMaxMm": 16.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-046",
    "calibre": ".38 Treinamento",
    "tipo": "Chumbo Ogival (CHOG)",
    "massaGramas": 8.1,
    "diametroMinMm": 9.07,
    "diametroMaxMm": 9.1,
    "comprimentoMinMm": 14.3,
    "comprimentoMaxMm": 14.3,
    "situacao": "estimada"
  },
  {
    "id": "cbc-047",
    "calibre": ".380 Auto",
    "tipo": "Encamisado Total Ogival (ETOG)",
    "massaGramas": 6.15,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 11.5,
    "comprimentoMaxMm": 11.5,
    "situacao": "estimada"
  },
  {
    "id": "cbc-048",
    "calibre": ".380 Auto",
    "tipo": "Encamisado Total Ogival (ETOG)",
    "massaGramas": 5.83,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 11.0,
    "comprimentoMaxMm": 11.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-049",
    "calibre": ".380 Auto",
    "tipo": "Encamisado Total Ponta Oca (EXPO)",
    "massaGramas": 6.15,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 13.0,
    "comprimentoMaxMm": 13.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-050",
    "calibre": ".380 Auto",
    "tipo": "Totalmente Encamisado Encamisado Obturado (EOOG)",
    "massaGramas": 6.15,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 11.4,
    "comprimentoMaxMm": 11.4,
    "situacao": "estimada"
  },
  {
    "id": "cbc-051",
    "calibre": ".380 Auto + P Gold",
    "tipo": "Encamisado Total Ponta Oca (EXPO)",
    "massaGramas": 5.5,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 10.9,
    "comprimentoMaxMm": 10.9,
    "situacao": "estimada"
  },
  {
    "id": "cbc-052",
    "calibre": ".380 Auto + P Silver Point",
    "tipo": "Encamisado Total Ponta Oca (EXPO) Niquelado",
    "massaGramas": 6.15,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 11.5,
    "comprimentoMaxMm": 11.5,
    "situacao": "estimada"
  },
  {
    "id": "cbc-054",
    "calibre": ".380 Auto +P",
    "tipo": "Encamisado Total Ponta Oca (EXPO)",
    "massaGramas": 5.5,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 10.7,
    "comprimentoMaxMm": 10.7,
    "situacao": "estimada"
  },
  {
    "id": "cbc-055",
    "calibre": ".380 Treina",
    "tipo": "Chumbo Ogival (CHOG)",
    "massaGramas": 6.15,
    "diametroMinMm": 9.03,
    "diametroMaxMm": 9.05,
    "comprimentoMinMm": 11.6,
    "comprimentoMaxMm": 11.6,
    "situacao": "estimada"
  },
  {
    "id": "cbc-056",
    "calibre": ".38-40 Winchester",
    "tipo": "Chumbo Ponta Plana (CHPP)",
    "massaGramas": 11.66,
    "diametroMinMm": 10.1,
    "diametroMaxMm": 10.15,
    "comprimentoMinMm": 15.0,
    "comprimentoMaxMm": 15.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-057",
    "calibre": ".40 S&W",
    "tipo": "Encamisado Total Ponta Oca (EXPO)",
    "massaGramas": 11.66,
    "diametroMinMm": 10.14,
    "diametroMaxMm": 10.16,
    "comprimentoMinMm": 16.2,
    "comprimentoMaxMm": 16.2,
    "situacao": "estimada"
  },
  {
    "id": "cbc-058",
    "calibre": ".40 S&W",
    "tipo": "Encamisado Total Ponta Plana (ETPP)",
    "massaGramas": 11.66,
    "diametroMinMm": 10.14,
    "diametroMaxMm": 10.16,
    "comprimentoMinMm": 15.6,
    "comprimentoMaxMm": 15.6,
    "situacao": "estimada"
  },
  {
    "id": "cbc-059",
    "calibre": ".40 S&W",
    "tipo": "Chumbo Semicanto Vivo (CSCV)",
    "massaGramas": 10.37,
    "diametroMinMm": 10.14,
    "diametroMaxMm": 10.16,
    "comprimentoMinMm": 15.4,
    "comprimentoMaxMm": 15.4,
    "situacao": "estimada"
  },
  {
    "id": "cbc-060",
    "calibre": ".40 S&W",
    "tipo": "Encamisado Total Ponta Oca (EXPO)",
    "massaGramas": 10.0,
    "diametroMinMm": 10.14,
    "diametroMaxMm": 10.16,
    "comprimentoMinMm": 13.9,
    "comprimentoMaxMm": 13.9,
    "situacao": "estimada"
  },
  {
    "id": "cbc-061",
    "calibre": ".40 S&W",
    "tipo": "Encamisado Total Ponta Oca (EXPO)",
    "massaGramas": 10.0,
    "diametroMinMm": 10.14,
    "diametroMaxMm": 10.16,
    "comprimentoMinMm": 14.0,
    "comprimentoMaxMm": 14.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-062",
    "calibre": ".40 S&W",
    "tipo": "Totalmente Encamisado Encamisado Obturado (EOOG)",
    "massaGramas": 11.66,
    "diametroMinMm": 10.14,
    "diametroMaxMm": 10.16,
    "comprimentoMinMm": 15.65,
    "comprimentoMaxMm": 15.65,
    "situacao": "estimada"
  },
  {
    "id": "cbc-063",
    "calibre": ".40 S&W",
    "tipo": "Chumbo Ponta Plana (CHPP)",
    "massaGramas": 10.37,
    "diametroMinMm": 10.15,
    "diametroMaxMm": 10.17,
    "comprimentoMinMm": 14.8,
    "comprimentoMaxMm": 14.8,
    "situacao": "estimada"
  },
  {
    "id": "cbc-064",
    "calibre": ".40 S&W",
    "tipo": "Encamisado Total Ponta Plana (ETPP)",
    "massaGramas": 10.69,
    "diametroMinMm": 10.14,
    "diametroMaxMm": 10.16,
    "comprimentoMinMm": 14.45,
    "comprimentoMaxMm": 14.45,
    "situacao": "estimada"
  },
  {
    "id": "cbc-065",
    "calibre": ".44 Rem Magmum",
    "tipo": "Encamisado Total Ponta Plana (ETPP)",
    "massaGramas": 15.55,
    "diametroMinMm": 10.93,
    "diametroMaxMm": 10.95,
    "comprimentoMinMm": 17.4,
    "comprimentoMaxMm": 17.4,
    "situacao": "estimada"
  },
  {
    "id": "cbc-066",
    "calibre": ".44 Remington Magnum",
    "tipo": "Semiencamisado Ponta de Chumbo Plana (EXPP)",
    "massaGramas": 15.55,
    "diametroMinMm": 10.93,
    "diametroMaxMm": 10.95,
    "comprimentoMinMm": 17.7,
    "comprimentoMaxMm": 17.7,
    "situacao": "estimada"
  },
  {
    "id": "cbc-067",
    "calibre": ".44 S&W SPL",
    "tipo": "Chumbo Ponta Plana (CHPP)",
    "massaGramas": 15.55,
    "diametroMinMm": 10.95,
    "diametroMaxMm": 10.97,
    "comprimentoMinMm": 18.1,
    "comprimentoMaxMm": 18.1,
    "situacao": "estimada"
  },
  {
    "id": "cbc-068",
    "calibre": ".44-40 Winchester",
    "tipo": "Chumbo Ponta Plana (CHPP)",
    "massaGramas": 12.96,
    "diametroMinMm": 10.82,
    "diametroMaxMm": 10.85,
    "comprimentoMinMm": 15.0,
    "comprimentoMaxMm": 15.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-069",
    "calibre": ".44-40 Winchester",
    "tipo": "Chumbo Ponta Plana (CHPP)",
    "massaGramas": 14.58,
    "diametroMinMm": 10.82,
    "diametroMaxMm": 10.85,
    "comprimentoMinMm": 16.8,
    "comprimentoMaxMm": 16.8,
    "situacao": "estimada"
  },
  {
    "id": "cbc-070",
    "calibre": ".45 Auto",
    "tipo": "Encamisado Total Ogival (ETOG)",
    "massaGramas": 14.9,
    "diametroMinMm": 11.45,
    "diametroMaxMm": 11.48,
    "comprimentoMinMm": 16.8,
    "comprimentoMaxMm": 16.8,
    "situacao": "estimada"
  },
  {
    "id": "cbc-071",
    "calibre": ".45 Auto",
    "tipo": "Encamisado Total Semicanto Vivo (ESCV)",
    "massaGramas": 14.9,
    "diametroMinMm": 11.45,
    "diametroMaxMm": 11.48,
    "comprimentoMinMm": 17.2,
    "comprimentoMaxMm": 17.2,
    "situacao": "estimada"
  },
  {
    "id": "cbc-072",
    "calibre": ".45 Auto",
    "tipo": "Chumbo Semicanto Vivo (CSCV)",
    "massaGramas": 12.96,
    "diametroMinMm": 11.47,
    "diametroMaxMm": 11.5,
    "comprimentoMinMm": 16.3,
    "comprimentoMaxMm": 16.3,
    "situacao": "estimada"
  },
  {
    "id": "cbc-073",
    "calibre": ".45 Auto + P",
    "tipo": "Encamisado Total Ponta Oca (EXPO)",
    "massaGramas": 12.0,
    "diametroMinMm": 11.45,
    "diametroMaxMm": 11.48,
    "comprimentoMinMm": 13.4,
    "comprimentoMaxMm": 13.4,
    "situacao": "estimada"
  },
  {
    "id": "cbc-074",
    "calibre": ".45 Auto + P",
    "tipo": "Encamisado Total Ponta Oca (EXPO)",
    "massaGramas": 12.0,
    "diametroMinMm": 11.45,
    "diametroMaxMm": 11.48,
    "comprimentoMinMm": 14.45,
    "comprimentoMaxMm": 14.45,
    "situacao": "estimada"
  },
  {
    "id": "cbc-075",
    "calibre": ".45 Auto + P",
    "tipo": "Encamisado Total Ponta Oca (EXPO)",
    "massaGramas": 14.9,
    "diametroMinMm": 11.45,
    "diametroMaxMm": 11.48,
    "comprimentoMinMm": 15.85,
    "comprimentoMaxMm": 15.85,
    "situacao": "estimada"
  },
  {
    "id": "cbc-076",
    "calibre": ".45 Colt",
    "tipo": "Chumbo Ponta Plana (CHPP)",
    "massaGramas": 16.2,
    "diametroMinMm": 11.51,
    "diametroMaxMm": 11.53,
    "comprimentoMinMm": 16.4,
    "comprimentoMaxMm": 16.4,
    "situacao": "estimada"
  },
  {
    "id": "cbc-079",
    "calibre": "12,70 x 99 mm (.50) AP-HC",
    "tipo": "Encamisado Ponta Plana (ETPT)",
    "massaGramas": 49.25,
    "diametroMinMm": 12.95,
    "diametroMaxMm": 12.98,
    "comprimentoMinMm": 57.0,
    "comprimentoMaxMm": 57.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-080",
    "calibre": "12,70 x 99 mm (.50) API-HC",
    "tipo": "Encamisado Ponta Plana (ETPT)",
    "massaGramas": 46.8,
    "diametroMinMm": 12.95,
    "diametroMaxMm": 12.98,
    "comprimentoMinMm": 57.0,
    "comprimentoMaxMm": 57.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-081",
    "calibre": "12,70 x 99 mm (.50) Comum M2",
    "tipo": "Encamisado Ponta Plana (ETPT)",
    "massaGramas": 45.23,
    "diametroMinMm": 12.95,
    "diametroMaxMm": 12.98,
    "comprimentoMinMm": 57.7,
    "comprimentoMaxMm": 57.7,
    "situacao": "estimada"
  },
  {
    "id": "cbc-082",
    "calibre": "12,70 x 99 mm (.50) Comum M33",
    "tipo": "Encamisado Ponta Plana (ETPT)",
    "massaGramas": 42.44,
    "diametroMinMm": 12.95,
    "diametroMaxMm": 12.98,
    "comprimentoMinMm": 57.7,
    "comprimentoMaxMm": 57.7,
    "situacao": "estimada"
  },
  {
    "id": "cbc-084",
    "calibre": "12,70 x 99 mm (.50) Incendiário M1",
    "tipo": "Encamisado Ponta Plana (ETPP)",
    "massaGramas": 40.82,
    "diametroMinMm": 12.95,
    "diametroMaxMm": 12.98,
    "comprimentoMinMm": 58.2,
    "comprimentoMaxMm": 58.2,
    "situacao": "estimada"
  },
  {
    "id": "cbc-085",
    "calibre": "12,70 x 99 mm (.50) Perfurante Incendiário M8",
    "tipo": "Encamisado Ponta Plana (ETPP)",
    "massaGramas": 42.64,
    "diametroMinMm": 12.95,
    "diametroMaxMm": 12.98,
    "comprimentoMinMm": 58.2,
    "comprimentoMaxMm": 58.2,
    "situacao": "estimada"
  },
  {
    "id": "cbc-086",
    "calibre": "12,70 x 99 mm (.50) Perfurante M2",
    "tipo": "Encamisado Ponta Plana (ETPP)",
    "massaGramas": 45.5,
    "diametroMinMm": 12.95,
    "diametroMaxMm": 12.98,
    "comprimentoMinMm": 57.7,
    "comprimentoMaxMm": 57.7,
    "situacao": "estimada"
  },
  {
    "id": "cbc-087",
    "calibre": "12,70 x 99 mm (.50) Perfurante/Incendiário/Traçcante M20",
    "tipo": "Encamisado Ponta Plana (ETPP)",
    "massaGramas": 39.65,
    "diametroMinMm": 12.95,
    "diametroMaxMm": 12.98,
    "comprimentoMinMm": 58.7,
    "comprimentoMaxMm": 58.7,
    "situacao": "estimada"
  },
  {
    "id": "cbc-088",
    "calibre": "12,70 x 99 mm (.50) Traçante M17",
    "tipo": "Encamisado Ponta Plana (ETPP)",
    "massaGramas": 40.82,
    "diametroMinMm": 12.95,
    "diametroMaxMm": 12.98,
    "comprimentoMinMm": 61.0,
    "comprimentoMaxMm": 61.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-089",
    "calibre": "12,70 x 99 mm (.50) Traçante M33",
    "tipo": "Encamisado Ponta Plana (ETPP)",
    "massaGramas": 37.84,
    "diametroMinMm": 12.95,
    "diametroMaxMm": 12.98,
    "comprimentoMinMm": 58.0,
    "comprimentoMaxMm": 58.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-090",
    "calibre": "40 S&W",
    "tipo": "Encamisado Total Ponta Oca (EXPO)",
    "massaGramas": 11.66,
    "diametroMinMm": 10.14,
    "diametroMaxMm": 10.16,
    "comprimentoMinMm": 15.75,
    "comprimentoMaxMm": 15.75,
    "situacao": "estimada"
  },
  {
    "id": "cbc-091",
    "calibre": "5,56 x 45 mm Comum (M193)",
    "tipo": "Encamisado Total Ponta Aguda(ETPT)",
    "massaGramas": 3.56,
    "diametroMinMm": 5.68,
    "diametroMaxMm": 5.7,
    "comprimentoMinMm": 18.8,
    "comprimentoMaxMm": 18.8,
    "situacao": "estimada"
  },
  {
    "id": "cbc-092",
    "calibre": "5,56 x 45 mm Festim",
    "tipo": "Encamisado Total Ponta Aguda (ETPT)",
    "massaGramas": 3.37,
    "diametroMinMm": 5.68,
    "diametroMaxMm": 5.7,
    "comprimentoMinMm": 23.0,
    "comprimentoMaxMm": 23.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-093",
    "calibre": "5,56 x 45 mm Lança Granada",
    "tipo": "Encamisado Total Ponta Aguda (ETPT)",
    "massaGramas": 3.37,
    "diametroMinMm": 5.68,
    "diametroMaxMm": 5.7,
    "comprimentoMinMm": 23.0,
    "comprimentoMaxMm": 23.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-094",
    "calibre": "5,56 x 45 mm SS-109",
    "tipo": "Encamisado Total Ponta Aguda (ETPT)",
    "massaGramas": 4.0,
    "diametroMinMm": 5.68,
    "diametroMaxMm": 5.7,
    "comprimentoMinMm": 23.1,
    "comprimentoMaxMm": 23.1,
    "situacao": "estimada"
  },
  {
    "id": "cbc-095",
    "calibre": "5,56 x 45 mm Traçan TE",
    "tipo": "Encamisado Total Ponta Aguda (ETPT)",
    "massaGramas": 3.37,
    "diametroMinMm": 5.68,
    "diametroMaxMm": 5.7,
    "comprimentoMinMm": 23.0,
    "comprimentoMaxMm": 23.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-096",
    "calibre": "6,5 x 55 mm",
    "tipo": "Encamisado Total (ETPT) Ponta Aguda",
    "massaGramas": 9.3,
    "diametroMinMm": 6.69,
    "diametroMaxMm": 6.71,
    "comprimentoMinMm": 33.5,
    "comprimentoMaxMm": 33.5,
    "situacao": "estimada"
  },
  {
    "id": "cbc-097",
    "calibre": "7 x 57 mm Mauser",
    "tipo": "Encamisado Total Ogival Ponta Aguda (ETPT)",
    "massaGramas": 10.5,
    "diametroMinMm": 7.26,
    "diametroMaxMm": 7.3,
    "comprimentoMinMm": 35.5,
    "comprimentoMaxMm": 35.5,
    "situacao": "estimada"
  },
  {
    "id": "cbc-098",
    "calibre": "7,62 x 39 mm",
    "tipo": "Encamisado Total Ogival Ponta Aguda (ETPT)",
    "massaGramas": 7.9,
    "diametroMinMm": 7.81,
    "diametroMaxMm": 7.83,
    "comprimentoMinMm": 23.0,
    "comprimentoMaxMm": 23.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-099",
    "calibre": "7,62 x 51 mm",
    "tipo": "Encamisado Total (ETPT) Ponta Aguda",
    "massaGramas": 9.33,
    "diametroMinMm": 7.81,
    "diametroMaxMm": 7.83,
    "comprimentoMinMm": 28.2,
    "comprimentoMaxMm": 28.2,
    "situacao": "estimada"
  },
  {
    "id": "cbc-100",
    "calibre": "7,62 x 51 mm (Match)",
    "tipo": "Encamisado Total (ETPT) Ponta Aguda",
    "massaGramas": 10.5,
    "diametroMinMm": 7.81,
    "diametroMaxMm": 7.83,
    "comprimentoMinMm": 30.0,
    "comprimentoMaxMm": 30.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-101",
    "calibre": "7,62 x 51 mm AP-HC",
    "tipo": "Encamisado Total (ETPT) Ponta Aguda",
    "massaGramas": 8.3,
    "diametroMinMm": 7.81,
    "diametroMaxMm": 7.83,
    "comprimentoMinMm": 29.0,
    "comprimentoMaxMm": 29.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-102",
    "calibre": "7,62 x 51 mm Festim",
    "tipo": "Encamisado Total (ETPT) Ponta Aguda",
    "massaGramas": 9.4,
    "diametroMinMm": 7.81,
    "diametroMaxMm": 7.83,
    "comprimentoMinMm": 35.5,
    "comprimentoMaxMm": 35.5,
    "situacao": "estimada"
  },
  {
    "id": "cbc-103",
    "calibre": "7,62 x 51 mm Incendiário",
    "tipo": "Encamisado Total (ETPT) Ponta Aguda",
    "massaGramas": 9.4,
    "diametroMinMm": 7.81,
    "diametroMaxMm": 7.83,
    "comprimentoMinMm": 35.5,
    "comprimentoMaxMm": 35.5,
    "situacao": "estimada"
  },
  {
    "id": "cbc-104",
    "calibre": "7,62 x 51 mm Lança Granada",
    "tipo": "Encamisado Total (ETPT) Ponta Aguda",
    "massaGramas": 9.4,
    "diametroMinMm": 7.81,
    "diametroMaxMm": 7.83,
    "comprimentoMinMm": 35.5,
    "comprimentoMaxMm": 35.5,
    "situacao": "estimada"
  },
  {
    "id": "cbc-105",
    "calibre": "7,62 x 51 mm perfurante",
    "tipo": "Encamisado Total (ETPT) Ponta Aguda",
    "massaGramas": 9.52,
    "diametroMinMm": 7.81,
    "diametroMaxMm": 7.83,
    "comprimentoMinMm": 32.0,
    "comprimentoMaxMm": 32.0,
    "situacao": "estimada"
  },
  {
    "id": "cbc-106",
    "calibre": "7,62 x 51 mm Traçante",
    "tipo": "Encamisado Total (ETPT) Ponta Aguda",
    "massaGramas": 8.75,
    "diametroMinMm": 7.81,
    "diametroMaxMm": 7.83,
    "comprimentoMinMm": 33.3,
    "comprimentoMaxMm": 33.3,
    "situacao": "estimada"
  },
  {
    "id": "cbc-107",
    "calibre": "7,62 x 63 mm (.30-06) PSP",
    "tipo": "Encamisado Ponta de Chumbo (EXPT)",
    "massaGramas": 9.72,
    "diametroMinMm": 7.81,
    "diametroMaxMm": 7.83,
    "comprimentoMinMm": 28.6,
    "comprimentoMaxMm": 28.6,
    "situacao": "estimada"
  },
  {
    "id": "cbc-108",
    "calibre": "7,62 x 63 mm Festim",
    "tipo": "Encamisado Ponta de Chumbo (EXPT)",
    "massaGramas": 9.72,
    "diametroMinMm": 7.81,
    "diametroMaxMm": 7.83,
    "comprimentoMinMm": 28.6,
    "comprimentoMaxMm": 28.6,
    "situacao": "estimada"
  },
  {
    "id": "cbc-109",
    "calibre": "7,62 x 63 mm Incendiário",
    "tipo": "Encamisado Total Ponta Aguda (ETPT)",
    "massaGramas": 9.72,
    "diametroMinMm": 7.81,
    "diametroMaxMm": 7.83,
    "comprimentoMinMm": 37.3,
    "comprimentoMaxMm": 37.3,
    "situacao": "estimada"
  },
  {
    "id": "cbc-110",
    "calibre": "7,62 x 63 mm Perfurante",
    "tipo": "Encamisado Total Ponta Aguda (ETPT)",
    "massaGramas": 10.7,
    "diametroMinMm": 7.81,
    "diametroMaxMm": 7.83,
    "comprimentoMinMm": 35.9,
    "comprimentoMaxMm": 35.9,
    "situacao": "estimada"
  },
  {
    "id": "cbc-111",
    "calibre": "7,62 x 63 mm Traçante",
    "tipo": "Encamisado Total Ponta Aguda (ETPT)",
    "massaGramas": 9.33,
    "diametroMinMm": 7.81,
    "diametroMaxMm": 7.83,
    "comprimentoMinMm": 34.9,
    "comprimentoMaxMm": 34.9,
    "situacao": "estimada"
  },
  {
    "id": "cbc-112",
    "calibre": "7,62x63 mm (.30-06)",
    "tipo": "Encamisado Total Ponta Aguda (ETPT)",
    "massaGramas": 9.72,
    "diametroMinMm": 7.81,
    "diametroMaxMm": 7.83,
    "comprimentoMinMm": 27.2,
    "comprimentoMaxMm": 27.2,
    "situacao": "estimada"
  },
  {
    "id": "cbc-113",
    "calibre": "9 mm Luger",
    "tipo": "Encamisado Total Ponta Oca (EXPO)",
    "massaGramas": 8.03,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 15.4,
    "comprimentoMaxMm": 15.4,
    "situacao": "estimada"
  },
  {
    "id": "cbc-114",
    "calibre": "9 mm Luger",
    "tipo": "Totalmente Encamisado Encamisado Obturado (EOOG)",
    "massaGramas": 8.03,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 15.4,
    "comprimentoMaxMm": 15.4,
    "situacao": "estimada"
  },
  {
    "id": "cbc-115",
    "calibre": "9 mm Luger",
    "tipo": "Totalmente Encamisado Encamisado Obturado (EOOG)",
    "massaGramas": 7.45,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 14.75,
    "comprimentoMaxMm": 14.75,
    "situacao": "estimada"
  },
  {
    "id": "cbc-116",
    "calibre": "9 mm Luger + P",
    "tipo": "Encamisado Total Ponta Oca (EXPO)",
    "massaGramas": 7.45,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 14.75,
    "comprimentoMaxMm": 14.75,
    "situacao": "estimada"
  },
  {
    "id": "cbc-117",
    "calibre": "9 mm Luger Subsônico (PSP)",
    "tipo": "Encamisado Total Ponta Plana (ETPP)",
    "massaGramas": 9.52,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 16.95,
    "comprimentoMaxMm": 16.95,
    "situacao": "estimada"
  },
  {
    "id": "cbc-118",
    "calibre": "9 mm Luger Subsônico (PSP)",
    "tipo": "Encamisado Total Ponta Oca (EXPO)",
    "massaGramas": 9.52,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 16.9,
    "comprimentoMaxMm": 16.9,
    "situacao": "estimada"
  },
  {
    "id": "cbc-119",
    "calibre": "9 mm Luger Subsônico (PSP)",
    "tipo": "Encamisado Ponta de Chumbo (EXOG)",
    "massaGramas": 8.03,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 14.9,
    "comprimentoMaxMm": 14.9,
    "situacao": "estimada"
  },
  {
    "id": "cbc-120",
    "calibre": "9x19 mm Luger",
    "tipo": "Encamisado Total Ogival (ETOG)",
    "massaGramas": 8.03,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 15.4,
    "comprimentoMaxMm": 15.4,
    "situacao": "estimada"
  },
  {
    "id": "cbc-121",
    "calibre": "9x19 mm Luger",
    "tipo": "Encamisado Total Ogival (ETOG)",
    "massaGramas": 7.45,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 13.9,
    "comprimentoMaxMm": 13.9,
    "situacao": "estimada"
  },
  {
    "id": "cbc-122",
    "calibre": "9x19 mm Luger",
    "tipo": "Encamisado Ponta Plana “Fiat\" (EXPP)",
    "massaGramas": 6.15,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 11.7,
    "comprimentoMaxMm": 11.7,
    "situacao": "estimada"
  },
  {
    "id": "cbc-123",
    "calibre": "9x19 mm Luger",
    "tipo": "Encamisado Total Ponta Oca (EXPO)",
    "massaGramas": 7.45,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 13.9,
    "comprimentoMaxMm": 13.9,
    "situacao": "estimada"
  },
  {
    "id": "cbc-124",
    "calibre": "9x19 mm Luger",
    "tipo": "Chumbo Ogival (CHOG)",
    "massaGramas": 8.03,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 15.6,
    "comprimentoMaxMm": 15.6,
    "situacao": "estimada"
  },
  {
    "id": "cbc-125",
    "calibre": "9x19 mm Luger +P+",
    "tipo": "Encamisado Total Ponta Plana (EXPO)",
    "massaGramas": 9.33,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 13.9,
    "comprimentoMaxMm": 13.9,
    "situacao": "estimada"
  },
  {
    "id": "cbc-126",
    "calibre": "9x19 mm Luger Clean Range",
    "tipo": "TMJ",
    "massaGramas": 8.03,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 15.6,
    "comprimentoMaxMm": 15.6,
    "situacao": "estimada"
  },
  {
    "id": "cbc-127",
    "calibre": "9x19 mm Luger Clean Range",
    "tipo": "Encamisado - FLAT",
    "massaGramas": 6.15,
    "diametroMinMm": 9.0,
    "diametroMaxMm": 9.02,
    "comprimentoMinMm": 11.7,
    "comprimentoMaxMm": 11.7,
    "situacao": "estimada"
  },
  {
    "id": "computador-009",
    "calibre": ".320 E. V.",
    "tipo": "Variante E. V.",
    "massaGramas": 4.865,
    "diametroMinMm": 7.3,
    "diametroMaxMm": 7.5,
    "comprimentoMinMm": 12.5,
    "comprimentoMaxMm": 12.6,
    "situacao": "estimada"
  },
  {
    "id": "computador-018",
    "calibre": ".38 SPL",
    "tipo": "ETOG",
    "massaGramas": 8.06,
    "diametroMinMm": 9,
    "diametroMaxMm": 9.1,
    "comprimentoMinMm": 15.2,
    "comprimentoMaxMm": 15.3,
    "situacao": "estimada"
  },
  {
    "id": "computador-020",
    "calibre": ".38 S&W Longo",
    "tipo": "Tipo não informado",
    "massaGramas": 10.219,
    "diametroMinMm": 8.7,
    "diametroMaxMm": 9,
    "comprimentoMinMm": 18.5,
    "comprimentoMaxMm": 19,
    "situacao": "estimada"
  },
  {
    "id": "computador-021",
    "calibre": ".38 S&W Longo",
    "tipo": "Canto vivo",
    "massaGramas": 9.509,
    "diametroMinMm": 8.7,
    "diametroMaxMm": 9,
    "comprimentoMinMm": 16.2,
    "comprimentoMaxMm": 16.3,
    "situacao": "estimada"
  },
  {
    "id": "computador-024",
    "calibre": ".380 Auto",
    "tipo": "Variante E. V.",
    "massaGramas": 7.542,
    "diametroMinMm": 8.6,
    "diametroMaxMm": 8.9,
    "comprimentoMinMm": 13.7,
    "comprimentoMaxMm": 14,
    "situacao": "estimada"
  },
  {
    "id": "computador-027",
    "calibre": ".45 Auto Rim",
    "tipo": "Tipo não informado",
    "massaGramas": 14.775,
    "diametroMinMm": 10.6,
    "diametroMaxMm": 11.1,
    "comprimentoMinMm": 20,
    "comprimentoMaxMm": 20.6,
    "situacao": "estimada"
  },
  {
    "id": "computador-029",
    "calibre": ".45 M4",
    "tipo": "Tipo não informado",
    "massaGramas": 14.99,
    "diametroMinMm": 11.4,
    "diametroMaxMm": 11.5,
    "comprimentoMinMm": 17,
    "comprimentoMaxMm": 17.2,
    "situacao": "estimada"
  },
  {
    "id": "computador-030",
    "calibre": ".32-20 Winchester",
    "tipo": "Tipo não informado",
    "massaGramas": 7.371,
    "diametroMinMm": 7.8,
    "diametroMaxMm": 7.9,
    "comprimentoMinMm": 16.1,
    "comprimentoMaxMm": 16.3,
    "situacao": "estimada"
  },
  {
    "id": "computador-034",
    "calibre": "7,63 mm",
    "tipo": "Tipo não informado",
    "massaGramas": 5.32,
    "diametroMinMm": 7.6,
    "diametroMaxMm": 7.8,
    "comprimentoMinMm": 13.6,
    "comprimentoMaxMm": 13.7,
    "situacao": "estimada"
  },
  {
    "id": "cbc-2026-38tpc",
    "calibre": ".38 TPC",
    "tipo": "ETOG",
    "massaGramas": 8.035,
    "diametroMinMm": null,
    "diametroMaxMm": null,
    "comprimentoMinMm": null,
    "comprimentoMaxMm": null,
    "situacao": "estimada"
  },
  {
    "id": "cbc-2026-10auto",
    "calibre": "10 mm Auto",
    "tipo": "ETPP",
    "massaGramas": 11.664,
    "diametroMinMm": null,
    "diametroMaxMm": null,
    "comprimentoMinMm": null,
    "comprimentoMaxMm": null,
    "situacao": "estimada"
  },
  {
    "id": "cbc-2026-38super",
    "calibre": ".38 Super Auto",
    "tipo": "ETOG",
    "massaGramas": 8.1,
    "diametroMinMm": null,
    "diametroMaxMm": null,
    "comprimentoMinMm": null,
    "comprimentoMaxMm": null,
    "situacao": "estimada"
  },
  {
    "id": "pericial-40-cxpo",
    "calibre": ".40 S&W",
    "tipo": "CXPO",
    "massaGramas": 8.445,
    "diametroMinMm": null,
    "diametroMaxMm": null,
    "comprimentoMinMm": 15.9,
    "comprimentoMaxMm": 15.9,
    "situacao": "estimada"
  },
  {
    "id": "pericial-44wcf-chog",
    "calibre": ".44 WCF",
    "tipo": "CHOG",
    "massaGramas": 15.94,
    "diametroMinMm": null,
    "diametroMaxMm": null,
    "comprimentoMinMm": 15.41,
    "comprimentoMaxMm": 15.41,
    "situacao": "estimada"
  },
  {
    "id": "pericial-44rem-sepo",
    "calibre": ".44 Rem Magnum",
    "tipo": "SEPO",
    "massaGramas": 15.614,
    "diametroMinMm": null,
    "diametroMaxMm": null,
    "comprimentoMinMm": 17.21,
    "comprimentoMaxMm": 17.21,
    "situacao": "estimada"
  }
];
