import {
  AlertCircle,
  Anchor,
  Award,
  Axe,
  BadgeCheck,
  Banknote,
  Beaker,
  Bell,
  Bike,
  Binary,
  Bomb,
  Bone,
  BookOpen,
  BookText,
  Bookmark,
  Box,
  BrainCircuit,
  Briefcase,
  Building,
  Bus,
  Calendar,
  Camera,
  Car,
  CarFront,
  Cctv,
  CheckCircle,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Compass,
  Component,
  Copy,
  Cpu,
  Crosshair,
  Crown,
  Database,
  Dna,
  DollarSign,
  Drill,
  Droplets,
  File,
  FileSearch,
  FileText,
  FileWarning,
  Fingerprint,
  Flag,
  Flame,
  Flashlight,
  FlaskConical,
  FlaskRound,
  Folder,
  Footprints,
  Gavel,
  Gem,
  Glasses,
  Globe,
  Hammer,
  HardDrive,
  Heart,
  HelpCircle,
  Image,
  Info,
  Key,
  Laptop,
  Layers,
  Layout,
  Leaf,
  Lock,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  MessageSquare,
  Microscope,
  Monitor,
  Music,
  Navigation,
  NotebookPen,
  PawPrint,
  Phone,
  Pill,
  Plane,
  Printer,
  Puzzle,
  Radio,
  Router,
  Ruler,
  Satellite,
  Scale,
  Scan,
  ScanEye,
  ScanFace,
  Scissors,
  Server,
  Settings,
  Shell,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  Ship,
  Shovel,
  Siren,
  Skull,
  Smartphone,
  Star,
  Sword,
  Swords,
  Syringe,
  Tag,
  Target,
  TestTube,
  TestTubes,
  Thermometer,
  ToolCase,
  Trophy,
  Truck,
  Tv,
  Usb,
  User,
  UserCheck,
  Users,
  Video,
  Wallet,
  Weight,
  Wifi,
  Wind,
  Wrench,
  XCircle,
  Zap,
  type LucideIcon,
} from 'lucide-react';

const iconesCategoria: Record<string, LucideIcon> = {
  AlertCircle, Anchor, Award, Axe, BadgeCheck, Banknote, Beaker, Bell, Bike, Binary,
  Bomb, Bone, BookOpen, BookText, Bookmark, Box, BrainCircuit, Briefcase, Building,
  Bus, Calendar, Camera, Car, CarFront, Cctv, CheckCircle, ClipboardCheck,
  ClipboardList, Clock, Compass, Component, Copy, Cpu, Crosshair, Crown, Database,
  Dna, DollarSign, Drill, Droplets, File, FileSearch, FileText, FileWarning,
  Fingerprint, Flag, Flame, Flashlight, FlaskConical, FlaskRound, Folder, Footprints,
  Gavel, Gem, Glasses, Globe, Hammer, HardDrive, Heart, HelpCircle, Image, Info, Key,
  Laptop, Layers, Layout, Leaf, Lock, Mail, Map, MapPin, Medal, Megaphone,
  MessageSquare, Microscope, Monitor, Music, Navigation, NotebookPen, PawPrint, Phone,
  Pill, Plane, Printer, Puzzle, Radio, Router, Ruler, Satellite, Scale, Scan, ScanEye,
  ScanFace, Scissors, Server, Settings, Shell, Shield, ShieldAlert, ShieldCheck,
  ShieldOff, Ship, Shovel, Siren, Skull, Smartphone, Star, Sword, Swords, Syringe,
  Tag, Target, TestTube, TestTubes, Thermometer, Tool: ToolCase, Trophy, Truck, Tv,
  Usb, User, UserCheck, Users, Video, Wallet, Weight, Wifi, Wind, Wrench, XCircle, Zap,
};

export function obterIconeCategoria(nome: string | null | undefined, fallback: LucideIcon = Tag): LucideIcon {
  return nome ? iconesCategoria[nome] ?? fallback : fallback;
}
