version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "monthly"
      day: "1"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 1
    groups:
      npm-versoes:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types: ["major", "minor", "patch"]
      npm-seguranca:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "monthly"
      day: "1"
      time: "09:30"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 1
    groups:
      github-actions-versoes:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types: ["major", "minor", "patch"]
      github-actions-seguranca:
        applies-to: "security-updates"
        patterns:
          - "*"
